// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208233942_new6")]
    partial class new6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 5, 0, 48, 10, 944, DateTimeKind.Local).AddTicks(337),
                            Description = "Rerum consectetur et",
                            ProjectId = 3,
                            Title = "Small Wooden Computer",
                            UpdatedAt = new DateTime(2022, 4, 20, 10, 30, 2, 676, DateTimeKind.Local).AddTicks(6622)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 3, 21, 8, 53, 42, 820, DateTimeKind.Local).AddTicks(4521),
                            Description = "Sunt voluptas debiti",
                            ProjectId = 3,
                            Title = "Tasty Frozen Salad",
                            UpdatedAt = new DateTime(2023, 1, 10, 11, 30, 56, 711, DateTimeKind.Local).AddTicks(7415)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 31, 12, 29, 45, 102, DateTimeKind.Local).AddTicks(1875),
                            Description = "Et vero at fugit sin",
                            ProjectId = 3,
                            Title = "Sleek Fresh Pants",
                            UpdatedAt = new DateTime(2022, 11, 26, 7, 6, 47, 653, DateTimeKind.Local).AddTicks(2780)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 12, 19, 5, 26, 2, 996, DateTimeKind.Local).AddTicks(9641),
                            Description = "Quod veniam in rerum",
                            ProjectId = 3,
                            Title = "Incredible Cotton Shirt",
                            UpdatedAt = new DateTime(2022, 8, 14, 19, 43, 56, 878, DateTimeKind.Local).AddTicks(4105)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 13, 1, 49, 12, 567, DateTimeKind.Local).AddTicks(9648),
                            Description = "Sit nesciunt velit i",
                            ProjectId = 4,
                            Title = "Intelligent Concrete Pizza",
                            UpdatedAt = new DateTime(2023, 1, 29, 13, 7, 57, 149, DateTimeKind.Local).AddTicks(2569)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 26, 0, 38, 20, 16, DateTimeKind.Local).AddTicks(9010),
                            Description = "Expedita dignissimos",
                            ProjectId = 6,
                            Title = "Sleek Fresh Soap",
                            UpdatedAt = new DateTime(2023, 1, 14, 12, 37, 23, 259, DateTimeKind.Local).AddTicks(8020)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 30, 18, 9, 18, 393, DateTimeKind.Local).AddTicks(9404),
                            Description = "Aspernatur ipsa volu",
                            ProjectId = 8,
                            Title = "Unbranded Granite Salad",
                            UpdatedAt = new DateTime(2022, 6, 26, 2, 37, 58, 355, DateTimeKind.Local).AddTicks(2534)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 28, 13, 16, 34, 926, DateTimeKind.Local).AddTicks(3090),
                            Description = "Nihil non ut non nes",
                            ProjectId = 6,
                            Title = "Tasty Cotton Pants",
                            UpdatedAt = new DateTime(2022, 4, 15, 1, 35, 0, 33, DateTimeKind.Local).AddTicks(4192)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 12, 28, 10, 31, 5, 745, DateTimeKind.Local).AddTicks(6319),
                            Description = "Molestiae nemo accus",
                            ProjectId = 6,
                            Title = "Handcrafted Fresh Soap",
                            UpdatedAt = new DateTime(2023, 1, 9, 14, 51, 8, 715, DateTimeKind.Local).AddTicks(4241)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 5, 31, 8, 58, 56, 926, DateTimeKind.Local).AddTicks(1939),
                            Description = "Sit quas voluptatibu",
                            ProjectId = 10,
                            Title = "Fantastic Metal Bike",
                            UpdatedAt = new DateTime(2022, 10, 3, 21, 12, 45, 64, DateTimeKind.Local).AddTicks(7077)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 2, 19, 3, 56, 34, 524, DateTimeKind.Local).AddTicks(9791),
                            Description = "Sed necessitatibus t",
                            OwnerId = 3,
                            Title = "Gorgeous Metal Chips",
                            UpdatedAt = new DateTime(2022, 5, 1, 10, 14, 38, 498, DateTimeKind.Local).AddTicks(3205)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 8, 2, 9, 38, 14, 189, DateTimeKind.Local).AddTicks(4978),
                            Description = "Aut accusamus vitae ",
                            OwnerId = 2,
                            Title = "Handmade Cotton Gloves",
                            UpdatedAt = new DateTime(2022, 3, 21, 6, 42, 27, 705, DateTimeKind.Local).AddTicks(7917)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 6, 23, 31, 48, 572, DateTimeKind.Local).AddTicks(4917),
                            Description = "Ut soluta eligendi r",
                            OwnerId = 3,
                            Title = "Small Rubber Tuna",
                            UpdatedAt = new DateTime(2022, 6, 14, 8, 10, 19, 42, DateTimeKind.Local).AddTicks(6995)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 12, 10, 0, 12, 22, 114, DateTimeKind.Local).AddTicks(3990),
                            Description = "Ut autem explicabo u",
                            OwnerId = 1,
                            Title = "Intelligent Rubber Ball",
                            UpdatedAt = new DateTime(2022, 8, 4, 23, 36, 9, 168, DateTimeKind.Local).AddTicks(7057)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 3, 5, 6, 19, 51, 501, DateTimeKind.Local).AddTicks(1061),
                            Description = "Ut illo rerum. Ipsa ",
                            OwnerId = 3,
                            Title = "Refined Rubber Cheese",
                            UpdatedAt = new DateTime(2022, 3, 28, 4, 58, 10, 770, DateTimeKind.Local).AddTicks(1559)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 6, 22, 5, 53, 18, 632, DateTimeKind.Local).AddTicks(1248),
                            Description = "Natus esse eius quis",
                            OwnerId = 4,
                            Title = "Generic Fresh Salad",
                            UpdatedAt = new DateTime(2023, 1, 16, 21, 13, 37, 931, DateTimeKind.Local).AddTicks(3920)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 26, 16, 16, 15, 855, DateTimeKind.Local).AddTicks(3557),
                            Description = "Suscipit temporibus ",
                            OwnerId = 5,
                            Title = "Rustic Granite Chips",
                            UpdatedAt = new DateTime(2022, 2, 16, 9, 6, 4, 768, DateTimeKind.Local).AddTicks(8341)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 15, 23, 57, 51, 547, DateTimeKind.Local).AddTicks(2615),
                            Description = "Voluptas ut ullam. C",
                            OwnerId = 3,
                            Title = "Gorgeous Plastic Pizza",
                            UpdatedAt = new DateTime(2022, 4, 26, 11, 55, 47, 84, DateTimeKind.Local).AddTicks(1157)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 3, 13, 8, 47, 38, 518, DateTimeKind.Local).AddTicks(5919),
                            Description = "Autem est non. Porro",
                            OwnerId = 1,
                            Title = "Refined Wooden Sausages",
                            UpdatedAt = new DateTime(2023, 1, 31, 3, 14, 35, 419, DateTimeKind.Local).AddTicks(5572)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 12, 11, 0, 41, 5, 331, DateTimeKind.Local).AddTicks(6496),
                            Description = "Molestiae dolorum do",
                            OwnerId = 1,
                            Title = "Tasty Steel Salad",
                            UpdatedAt = new DateTime(2022, 8, 30, 13, 27, 8, 456, DateTimeKind.Local).AddTicks(598)
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Eloise3@gmail.com",
                            Name = "Natasha Roberts",
                            Password = "5y7mOr7KgO"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Caterina_Kuvalis@gmail.com",
                            Name = "Janet Weber",
                            Password = "saCj8vLPpB"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Kristoffer.Nikolaus@gmail.com",
                            Name = "Arthur DuBuque",
                            Password = "XNrm9_0FZR"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Katlyn_Mosciski21@hotmail.com",
                            Name = "Audra Klocko",
                            Password = "bwM3bEu0HE"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Ricardo31@gmail.com",
                            Name = "Golda Dietrich",
                            Password = "p6AOsPIdYc"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
