// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230212234108_updated3")]
    partial class updated3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 3, 7, 58, 22, 142, DateTimeKind.Local).AddTicks(3940),
                            Description = "Porro saepe ipsam ut",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Small Cotton Car",
                            UpdatedAt = new DateTime(2022, 10, 3, 14, 50, 43, 324, DateTimeKind.Local).AddTicks(6176)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 11, 29, 18, 10, 29, 386, DateTimeKind.Local).AddTicks(3129),
                            Description = "Itaque enim ab exerc",
                            IsCompleted = true,
                            ProjectId = 7,
                            Title = "Awesome Cotton Pants",
                            UpdatedAt = new DateTime(2022, 11, 3, 8, 18, 27, 353, DateTimeKind.Local).AddTicks(9140)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 12, 10, 9, 26, 31, 795, DateTimeKind.Local).AddTicks(759),
                            Description = "Hic omnis sit ut aut",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Awesome Granite Sausages",
                            UpdatedAt = new DateTime(2022, 11, 28, 15, 13, 34, 367, DateTimeKind.Local).AddTicks(6425)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 8, 4, 15, 24, 23, 960, DateTimeKind.Local).AddTicks(1068),
                            Description = "Consectetur et aut a",
                            IsCompleted = true,
                            ProjectId = 1,
                            Title = "Tasty Cotton Cheese",
                            UpdatedAt = new DateTime(2022, 5, 8, 14, 21, 49, 828, DateTimeKind.Local).AddTicks(7061)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 6, 3, 11, 10, 48, 662, DateTimeKind.Local).AddTicks(9038),
                            Description = "Facere maxime velit ",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Awesome Steel Table",
                            UpdatedAt = new DateTime(2022, 7, 28, 7, 47, 16, 346, DateTimeKind.Local).AddTicks(808)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 24, 11, 42, 10, 380, DateTimeKind.Local).AddTicks(8050),
                            Description = "Voluptas voluptatum ",
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Awesome Granite Gloves",
                            UpdatedAt = new DateTime(2023, 1, 13, 4, 43, 0, 791, DateTimeKind.Local).AddTicks(1253)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 3, 30, 12, 39, 33, 513, DateTimeKind.Local).AddTicks(5122),
                            Description = "Accusamus officiis q",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Sleek Metal Car",
                            UpdatedAt = new DateTime(2022, 9, 9, 3, 31, 17, 520, DateTimeKind.Local).AddTicks(631)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 6, 22, 4, 51, 55, 910, DateTimeKind.Local).AddTicks(9478),
                            Description = "Sequi qui eum nam do",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Generic Concrete Bacon",
                            UpdatedAt = new DateTime(2022, 6, 12, 19, 30, 11, 121, DateTimeKind.Local).AddTicks(1032)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 7, 26, 13, 40, 40, 422, DateTimeKind.Local).AddTicks(7090),
                            Description = "Minus excepturi susc",
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "Rustic Plastic Keyboard",
                            UpdatedAt = new DateTime(2022, 4, 30, 1, 23, 43, 766, DateTimeKind.Local).AddTicks(7808)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 26, 2, 29, 55, 755, DateTimeKind.Local).AddTicks(6164),
                            Description = "Velit minima cumque ",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Unbranded Granite Car",
                            UpdatedAt = new DateTime(2022, 4, 13, 14, 50, 9, 973, DateTimeKind.Local).AddTicks(2440)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 8, 19, 13, 28, 55, 434, DateTimeKind.Local).AddTicks(5104),
                            Description = "Aperiam quidem liber",
                            IsCompleted = true,
                            ProjectId = 10,
                            Title = "Handmade Concrete Salad",
                            UpdatedAt = new DateTime(2022, 12, 14, 11, 18, 16, 356, DateTimeKind.Local).AddTicks(3808)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 4, 20, 22, 2, 49, 191, DateTimeKind.Local).AddTicks(7544),
                            Description = "Et non dolores digni",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Generic Metal Ball",
                            UpdatedAt = new DateTime(2022, 11, 1, 20, 33, 47, 787, DateTimeKind.Local).AddTicks(5115)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 3, 25, 3, 56, 52, 543, DateTimeKind.Local).AddTicks(2257),
                            Description = "Ut cumque tempore di",
                            IsCompleted = true,
                            ProjectId = 10,
                            Title = "Rustic Cotton Sausages",
                            UpdatedAt = new DateTime(2023, 1, 27, 15, 37, 32, 70, DateTimeKind.Local).AddTicks(5045)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 5, 27, 14, 11, 44, 736, DateTimeKind.Local).AddTicks(9214),
                            Description = "Odit omnis unde aute",
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Tasty Metal Towels",
                            UpdatedAt = new DateTime(2023, 1, 18, 23, 20, 38, 911, DateTimeKind.Local).AddTicks(7767)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 6, 3, 21, 30, 19, 141, DateTimeKind.Local).AddTicks(1987),
                            Description = "In sequi laborum dol",
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Tasty Soft Computer",
                            UpdatedAt = new DateTime(2023, 1, 27, 17, 52, 11, 745, DateTimeKind.Local).AddTicks(61)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 3, 16, 0, 21, 3, 974, DateTimeKind.Local).AddTicks(9140),
                            Description = "Aut ratione beatae. ",
                            IsCompleted = true,
                            ProjectId = 7,
                            Title = "Handcrafted Metal Sausages",
                            UpdatedAt = new DateTime(2022, 6, 8, 16, 59, 45, 569, DateTimeKind.Local).AddTicks(1342)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 30, 21, 19, 22, 254, DateTimeKind.Local).AddTicks(4189),
                            Description = "Cupiditate autem deb",
                            IsCompleted = true,
                            ProjectId = 8,
                            Title = "Sleek Metal Chips",
                            UpdatedAt = new DateTime(2022, 3, 18, 17, 34, 54, 709, DateTimeKind.Local).AddTicks(9531)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 3, 9, 4, 32, 19, 243, DateTimeKind.Local).AddTicks(9689),
                            Description = "Aut perspiciatis ull",
                            IsCompleted = false,
                            ProjectId = 9,
                            Title = "Tasty Steel Pizza",
                            UpdatedAt = new DateTime(2022, 11, 15, 14, 33, 45, 818, DateTimeKind.Local).AddTicks(216)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 3, 20, 5, 30, 31, 546, DateTimeKind.Local).AddTicks(413),
                            Description = "Sed ea voluptates pl",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Fantastic Granite Car",
                            UpdatedAt = new DateTime(2022, 8, 8, 21, 55, 10, 953, DateTimeKind.Local).AddTicks(3879)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 5, 9, 8, 55, 4, 757, DateTimeKind.Local).AddTicks(3512),
                            Description = "Quia molestiae sunt ",
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Intelligent Granite Mouse",
                            UpdatedAt = new DateTime(2022, 5, 5, 8, 16, 27, 335, DateTimeKind.Local).AddTicks(6745)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 28, 8, 37, 54, 965, DateTimeKind.Local).AddTicks(9379),
                            Description = "Et et sint nihil nes",
                            OwnerId = 4,
                            Title = "Gorgeous Frozen Hat",
                            UpdatedAt = new DateTime(2022, 8, 3, 15, 20, 39, 111, DateTimeKind.Local).AddTicks(480)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 12, 11, 10, 38, 508, DateTimeKind.Local).AddTicks(3964),
                            Description = "Reprehenderit repreh",
                            OwnerId = 4,
                            Title = "Refined Steel Chicken",
                            UpdatedAt = new DateTime(2022, 7, 18, 2, 55, 42, 477, DateTimeKind.Local).AddTicks(2694)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 3, 12, 59, 31, 228, DateTimeKind.Local).AddTicks(5863),
                            Description = "Quo est consequatur ",
                            OwnerId = 5,
                            Title = "Generic Rubber Ball",
                            UpdatedAt = new DateTime(2022, 2, 25, 11, 7, 36, 177, DateTimeKind.Local).AddTicks(2618)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 8, 28, 11, 44, 49, 67, DateTimeKind.Local).AddTicks(1253),
                            Description = "Libero qui velit eos",
                            OwnerId = 4,
                            Title = "Gorgeous Fresh Gloves",
                            UpdatedAt = new DateTime(2022, 12, 9, 20, 45, 37, 7, DateTimeKind.Local).AddTicks(167)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 8, 2, 0, 17, 53, 6, DateTimeKind.Local).AddTicks(7020),
                            Description = "Repellat mollitia es",
                            OwnerId = 4,
                            Title = "Unbranded Wooden Gloves",
                            UpdatedAt = new DateTime(2022, 4, 12, 17, 36, 13, 369, DateTimeKind.Local).AddTicks(958)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 2, 14, 13, 17, 18, 41, DateTimeKind.Local).AddTicks(6033),
                            Description = "Laborum iusto rem eo",
                            OwnerId = 2,
                            Title = "Fantastic Fresh Chicken",
                            UpdatedAt = new DateTime(2022, 3, 15, 19, 2, 42, 710, DateTimeKind.Local).AddTicks(2852)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 29, 8, 54, 9, 711, DateTimeKind.Local).AddTicks(2453),
                            Description = "Quasi aliquam animi ",
                            OwnerId = 5,
                            Title = "Tasty Metal Table",
                            UpdatedAt = new DateTime(2022, 12, 20, 12, 8, 42, 931, DateTimeKind.Local).AddTicks(848)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 25, 8, 16, 35, 184, DateTimeKind.Local).AddTicks(1145),
                            Description = "Laboriosam velit atq",
                            OwnerId = 2,
                            Title = "Awesome Rubber Pizza",
                            UpdatedAt = new DateTime(2022, 8, 15, 11, 37, 31, 488, DateTimeKind.Local).AddTicks(6071)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 8, 19, 22, 27, 32, 138, DateTimeKind.Local).AddTicks(2053),
                            Description = "Voluptate architecto",
                            OwnerId = 3,
                            Title = "Sleek Steel Car",
                            UpdatedAt = new DateTime(2022, 4, 20, 2, 12, 11, 89, DateTimeKind.Local).AddTicks(102)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 13, 19, 58, 32, 578, DateTimeKind.Local).AddTicks(6939),
                            Description = "Et inventore volupta",
                            OwnerId = 4,
                            Title = "Ergonomic Wooden Keyboard",
                            UpdatedAt = new DateTime(2022, 6, 28, 22, 25, 2, 373, DateTimeKind.Local).AddTicks(2960)
                        });
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Denis_Gerhold97@yahoo.com",
                            Name = "Gregorio Fritsch",
                            Password = "Tlh_xkHOd2",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "Edgar.White58@hotmail.com",
                            Name = "Lavina Batz",
                            Password = "gLoDcMAKr5",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "Fredrick_Beer60@hotmail.com",
                            Name = "Guy Bosco",
                            Password = "Tgz0G5Z6wb",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "Pearl.Trantow29@hotmail.com",
                            Name = "Chelsie Deckow",
                            Password = "yHMUoClmSn",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "Lenny_Watsica27@yahoo.com",
                            Name = "Kylee Adams",
                            Password = "5EcOndITa0",
                            RoleId = 0
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Participators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colab.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
