// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230212235007_updated4")]
    partial class updated4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 23, 58, 22, 426, DateTimeKind.Local).AddTicks(9294),
                            Description = "Architecto soluta no",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Intelligent Granite Shoes",
                            UpdatedAt = new DateTime(2022, 8, 25, 1, 10, 0, 270, DateTimeKind.Local).AddTicks(695)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 4, 8, 22, 25, 359, DateTimeKind.Local).AddTicks(5951),
                            Description = "Dolorem officiis qui",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Awesome Plastic Bacon",
                            UpdatedAt = new DateTime(2022, 4, 29, 17, 19, 49, 718, DateTimeKind.Local).AddTicks(4751)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 11, 8, 24, 21, 40, DateTimeKind.Local).AddTicks(838),
                            Description = "Mollitia ut necessit",
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Rustic Plastic Tuna",
                            UpdatedAt = new DateTime(2022, 11, 26, 22, 35, 27, 241, DateTimeKind.Local).AddTicks(9670)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 12, 6, 15, 22, 23, 108, DateTimeKind.Local).AddTicks(2175),
                            Description = "Fuga dolore vitae qu",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Practical Rubber Bacon",
                            UpdatedAt = new DateTime(2022, 10, 4, 23, 4, 37, 571, DateTimeKind.Local).AddTicks(777)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 5, 16, 10, 20, 10, 33, DateTimeKind.Local).AddTicks(3942),
                            Description = "Ut id fugiat iusto q",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Intelligent Rubber Bike",
                            UpdatedAt = new DateTime(2023, 2, 11, 4, 25, 44, 864, DateTimeKind.Local).AddTicks(1961)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 6, 22, 43, 8, 736, DateTimeKind.Local).AddTicks(2327),
                            Description = "Consequatur dignissi",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Practical Metal Pants",
                            UpdatedAt = new DateTime(2022, 3, 7, 18, 54, 13, 213, DateTimeKind.Local).AddTicks(5916)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 12, 6, 10, 41, 57, 193, DateTimeKind.Local).AddTicks(2404),
                            Description = "Odio ab eius assumen",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Generic Wooden Shirt",
                            UpdatedAt = new DateTime(2022, 10, 28, 12, 42, 26, 786, DateTimeKind.Local).AddTicks(7176)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 2, 15, 12, 20, 30, 335, DateTimeKind.Local).AddTicks(7120),
                            Description = "Eius cupiditate saep",
                            IsCompleted = false,
                            ProjectId = 10,
                            Title = "Handmade Metal Car",
                            UpdatedAt = new DateTime(2022, 12, 20, 17, 25, 20, 276, DateTimeKind.Local).AddTicks(2264)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 6, 14, 12, 36, 35, 284, DateTimeKind.Local).AddTicks(1213),
                            Description = "Maxime quasi deserun",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Generic Wooden Hat",
                            UpdatedAt = new DateTime(2023, 1, 6, 7, 9, 0, 723, DateTimeKind.Local).AddTicks(9110)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 11, 28, 23, 11, 43, 317, DateTimeKind.Local).AddTicks(9639),
                            Description = "Et impedit corrupti ",
                            IsCompleted = true,
                            ProjectId = 10,
                            Title = "Incredible Wooden Keyboard",
                            UpdatedAt = new DateTime(2022, 10, 3, 18, 16, 8, 706, DateTimeKind.Local).AddTicks(5453)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 9, 26, 20, 11, 58, 670, DateTimeKind.Local).AddTicks(5700),
                            Description = "Cumque cupiditate la",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Handcrafted Metal Sausages",
                            UpdatedAt = new DateTime(2023, 2, 10, 23, 42, 37, 562, DateTimeKind.Local).AddTicks(3002)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 2, 10, 11, 29, 0, 537, DateTimeKind.Local).AddTicks(1240),
                            Description = "Necessitatibus eaque",
                            IsCompleted = true,
                            ProjectId = 7,
                            Title = "Tasty Cotton Hat",
                            UpdatedAt = new DateTime(2022, 12, 27, 21, 49, 20, 457, DateTimeKind.Local).AddTicks(6851)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 4, 25, 14, 18, 7, 862, DateTimeKind.Local).AddTicks(5249),
                            Description = "Neque hic et aut lab",
                            IsCompleted = true,
                            ProjectId = 3,
                            Title = "Gorgeous Steel Cheese",
                            UpdatedAt = new DateTime(2022, 12, 3, 23, 31, 3, 941, DateTimeKind.Local).AddTicks(6848)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 8, 16, 2, 6, 0, 737, DateTimeKind.Local).AddTicks(7042),
                            Description = "Sit libero ducimus n",
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Handmade Frozen Car",
                            UpdatedAt = new DateTime(2022, 9, 5, 12, 3, 22, 421, DateTimeKind.Local).AddTicks(9429)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 10, 4, 14, 51, 26, 533, DateTimeKind.Local).AddTicks(8416),
                            Description = "Provident vel aliqua",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Awesome Plastic Gloves",
                            UpdatedAt = new DateTime(2022, 11, 14, 4, 19, 35, 15, DateTimeKind.Local).AddTicks(9865)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 8, 24, 23, 12, 24, 67, DateTimeKind.Local).AddTicks(1442),
                            Description = "Et eum excepturi. Et",
                            IsCompleted = true,
                            ProjectId = 7,
                            Title = "Handcrafted Fresh Ball",
                            UpdatedAt = new DateTime(2022, 3, 21, 6, 59, 59, 657, DateTimeKind.Local).AddTicks(8084)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 6, 9, 20, 58, 40, 706, DateTimeKind.Local).AddTicks(3292),
                            Description = "Ab ex nobis tenetur ",
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "Awesome Fresh Chicken",
                            UpdatedAt = new DateTime(2023, 1, 17, 4, 50, 15, 368, DateTimeKind.Local).AddTicks(9989)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 2, 12, 20, 39, 11, 469, DateTimeKind.Local).AddTicks(4864),
                            Description = "Maiores delectus del",
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "Gorgeous Metal Keyboard",
                            UpdatedAt = new DateTime(2022, 2, 13, 5, 51, 32, 976, DateTimeKind.Local).AddTicks(5581)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 6, 30, 19, 18, 25, 180, DateTimeKind.Local).AddTicks(7094),
                            Description = "Quisquam ipsa distin",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Generic Cotton Chips",
                            UpdatedAt = new DateTime(2022, 7, 13, 21, 18, 2, 679, DateTimeKind.Local).AddTicks(2253)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 10, 27, 15, 55, 49, 89, DateTimeKind.Local).AddTicks(1543),
                            Description = "Tempora sed voluptat",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Incredible Wooden Shirt",
                            UpdatedAt = new DateTime(2022, 11, 17, 6, 59, 15, 308, DateTimeKind.Local).AddTicks(6968)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 13, 10, 9, 27, 7, DateTimeKind.Local).AddTicks(5329),
                            Description = "Possimus molestiae a",
                            Title = "Generic Rubber Chicken",
                            UpdatedAt = new DateTime(2022, 2, 17, 14, 16, 6, 224, DateTimeKind.Local).AddTicks(1605)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 8, 24, 7, 29, 32, 21, DateTimeKind.Local).AddTicks(8134),
                            Description = "Repudiandae explicab",
                            Title = "Generic Steel Pizza",
                            UpdatedAt = new DateTime(2022, 9, 29, 17, 52, 25, 809, DateTimeKind.Local).AddTicks(857)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 7, 11, 0, 50, 10, 122, DateTimeKind.Local).AddTicks(9400),
                            Description = "Dolor neque quibusda",
                            Title = "Rustic Frozen Mouse",
                            UpdatedAt = new DateTime(2022, 6, 17, 23, 56, 25, 858, DateTimeKind.Local).AddTicks(7804)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 27, 12, 34, 58, 754, DateTimeKind.Local).AddTicks(8272),
                            Description = "Iure et ipsum fugiat",
                            Title = "Practical Rubber Keyboard",
                            UpdatedAt = new DateTime(2022, 3, 9, 4, 10, 9, 515, DateTimeKind.Local).AddTicks(4648)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 4, 9, 8, 30, 6, 658, DateTimeKind.Local).AddTicks(189),
                            Description = "Voluptas unde nemo t",
                            Title = "Small Plastic Keyboard",
                            UpdatedAt = new DateTime(2022, 5, 14, 7, 57, 56, 363, DateTimeKind.Local).AddTicks(1317)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 12, 12, 16, 14, 42, 732, DateTimeKind.Local).AddTicks(5860),
                            Description = "At deleniti animi qu",
                            Title = "Ergonomic Plastic Cheese",
                            UpdatedAt = new DateTime(2022, 3, 23, 16, 7, 31, 498, DateTimeKind.Local).AddTicks(2065)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 8, 18, 21, 50, 49, 19, DateTimeKind.Local).AddTicks(5132),
                            Description = "Et aut vel. Quasi ar",
                            Title = "Fantastic Frozen Sausages",
                            UpdatedAt = new DateTime(2022, 3, 10, 11, 55, 35, 92, DateTimeKind.Local).AddTicks(8547)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 11, 18, 9, 17, 706, DateTimeKind.Local).AddTicks(7741),
                            Description = "Voluptatem aspernatu",
                            Title = "Gorgeous Granite Salad",
                            UpdatedAt = new DateTime(2022, 10, 25, 15, 19, 13, 957, DateTimeKind.Local).AddTicks(9685)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 5, 22, 23, 58, 51, 124, DateTimeKind.Local).AddTicks(2147),
                            Description = "Quos consequatur ad ",
                            Title = "Gorgeous Rubber Shoes",
                            UpdatedAt = new DateTime(2022, 12, 17, 21, 43, 52, 621, DateTimeKind.Local).AddTicks(2084)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 8, 1, 22, 2, 27, 91, DateTimeKind.Local).AddTicks(3697),
                            Description = "Reprehenderit id arc",
                            Title = "Awesome Concrete Fish",
                            UpdatedAt = new DateTime(2022, 4, 5, 17, 56, 17, 789, DateTimeKind.Local).AddTicks(1618)
                        });
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Sofia.Larson86@hotmail.com",
                            IsAdmin = false,
                            Name = "Richie Mayer",
                            Password = "McxH2O8kwv"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Abigayle_Bruen@hotmail.com",
                            IsAdmin = false,
                            Name = "Jamar Kessler",
                            Password = "b7ULHvgPDH"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Nichole.Crist44@hotmail.com",
                            IsAdmin = false,
                            Name = "Ariane Windler",
                            Password = "Kh4VQQmkwv"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Nicklaus.Zboncak@yahoo.com",
                            IsAdmin = false,
                            Name = "Kian Kessler",
                            Password = "FR0LuP4rMs"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Myra.Terry26@hotmail.com",
                            IsAdmin = false,
                            Name = "Carlie Frami",
                            Password = "R5B5OgZX8g"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Participators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colab.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
