// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208205353_new3")]
    partial class new3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRefId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 11, 7, 14, 38, 12, 404, DateTimeKind.Local).AddTicks(483),
                            Description = "Ea voluptas dolor po",
                            ProjectRefId = 2,
                            Title = "Handcrafted Wooden Towels",
                            UpdatedAt = new DateTime(2022, 8, 24, 5, 39, 53, 332, DateTimeKind.Local).AddTicks(8537)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 21, 8, 13, 23, 90, DateTimeKind.Local).AddTicks(5948),
                            Description = "Sed eaque sint et te",
                            ProjectRefId = 2,
                            Title = "Gorgeous Concrete Bacon",
                            UpdatedAt = new DateTime(2022, 8, 28, 16, 15, 16, 870, DateTimeKind.Local).AddTicks(253)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 21, 22, 58, 36, 572, DateTimeKind.Local).AddTicks(3573),
                            Description = "Eos magni quibusdam ",
                            ProjectRefId = 4,
                            Title = "Sleek Cotton Shoes",
                            UpdatedAt = new DateTime(2022, 12, 7, 12, 56, 46, 249, DateTimeKind.Local).AddTicks(4337)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 11, 26, 16, 40, 38, 87, DateTimeKind.Local).AddTicks(5837),
                            Description = "Nulla qui illum tene",
                            ProjectRefId = 4,
                            Title = "Gorgeous Granite Gloves",
                            UpdatedAt = new DateTime(2022, 4, 1, 17, 58, 8, 138, DateTimeKind.Local).AddTicks(8774)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 7, 3, 52, 5, 442, DateTimeKind.Local).AddTicks(5640),
                            Description = "Vel temporibus ea. C",
                            ProjectRefId = 4,
                            Title = "Awesome Cotton Sausages",
                            UpdatedAt = new DateTime(2022, 8, 10, 1, 38, 33, 274, DateTimeKind.Local).AddTicks(8582)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 11, 4, 10, 6, 34, 160, DateTimeKind.Local).AddTicks(9545),
                            Description = "Error laudantium por",
                            ProjectRefId = 3,
                            Title = "Refined Rubber Hat",
                            UpdatedAt = new DateTime(2022, 6, 5, 7, 39, 54, 260, DateTimeKind.Local).AddTicks(9624)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 9, 14, 9, 21, 438, DateTimeKind.Local).AddTicks(760),
                            Description = "Quaerat non perspici",
                            ProjectRefId = 7,
                            Title = "Ergonomic Wooden Shoes",
                            UpdatedAt = new DateTime(2022, 6, 11, 23, 34, 38, 127, DateTimeKind.Local).AddTicks(3968)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 11, 14, 17, 21, 5, 604, DateTimeKind.Local).AddTicks(1754),
                            Description = "Aut quas sint et est",
                            ProjectRefId = 7,
                            Title = "Fantastic Granite Ball",
                            UpdatedAt = new DateTime(2022, 10, 21, 23, 29, 14, 928, DateTimeKind.Local).AddTicks(6806)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 11, 2, 22, 50, 32, 176, DateTimeKind.Local).AddTicks(7771),
                            Description = "Explicabo nesciunt b",
                            ProjectRefId = 10,
                            Title = "Intelligent Wooden Car",
                            UpdatedAt = new DateTime(2023, 1, 24, 23, 5, 23, 616, DateTimeKind.Local).AddTicks(1422)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 22, 17, 59, 47, 364, DateTimeKind.Local).AddTicks(9117),
                            Description = "Doloribus molestiae ",
                            ProjectRefId = 4,
                            Title = "Rustic Wooden Bike",
                            UpdatedAt = new DateTime(2022, 7, 22, 22, 38, 59, 702, DateTimeKind.Local).AddTicks(9934)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ownerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ownerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 11, 3, 29, 22, 831, DateTimeKind.Local).AddTicks(5820),
                            Description = "Reprehenderit nemo e",
                            Title = "Small Soft Shirt",
                            UpdatedAt = new DateTime(2023, 2, 5, 15, 2, 55, 783, DateTimeKind.Local).AddTicks(7249),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 3, 19, 7, 52, 135, DateTimeKind.Local).AddTicks(2534),
                            Description = "Id optio sunt earum.",
                            Title = "Handcrafted Metal Bacon",
                            UpdatedAt = new DateTime(2023, 2, 5, 0, 39, 47, 986, DateTimeKind.Local).AddTicks(5994),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 8, 25, 1, 51, 27, 728, DateTimeKind.Local).AddTicks(6937),
                            Description = "Minus velit facere d",
                            Title = "Refined Rubber Sausages",
                            UpdatedAt = new DateTime(2022, 7, 22, 1, 7, 22, 957, DateTimeKind.Local).AddTicks(4670),
                            ownerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 15, 8, 59, 48, 508, DateTimeKind.Local).AddTicks(662),
                            Description = "Quia et ut animi fac",
                            Title = "Awesome Rubber Shirt",
                            UpdatedAt = new DateTime(2022, 11, 26, 21, 46, 53, 247, DateTimeKind.Local).AddTicks(4449),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 30, 8, 33, 41, 476, DateTimeKind.Local).AddTicks(6677),
                            Description = "Incidunt est sunt co",
                            Title = "Generic Metal Keyboard",
                            UpdatedAt = new DateTime(2022, 3, 11, 22, 20, 11, 456, DateTimeKind.Local).AddTicks(4520),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 5, 12, 6, 54, 50, 970, DateTimeKind.Local).AddTicks(1784),
                            Description = "Culpa et molestiae i",
                            Title = "Intelligent Steel Table",
                            UpdatedAt = new DateTime(2022, 3, 25, 14, 38, 19, 422, DateTimeKind.Local).AddTicks(6014),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 6, 16, 4, 17, 41, 466, DateTimeKind.Local).AddTicks(737),
                            Description = "Corporis omnis volup",
                            Title = "Generic Frozen Mouse",
                            UpdatedAt = new DateTime(2023, 1, 23, 8, 26, 52, 755, DateTimeKind.Local).AddTicks(429),
                            ownerId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 6, 18, 15, 30, 1, 110, DateTimeKind.Local).AddTicks(7201),
                            Description = "Occaecati voluptatib",
                            Title = "Awesome Steel Salad",
                            UpdatedAt = new DateTime(2022, 7, 30, 19, 4, 48, 584, DateTimeKind.Local).AddTicks(1216),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 5, 30, 19, 27, 55, 131, DateTimeKind.Local).AddTicks(2908),
                            Description = "Molestias autem erro",
                            Title = "Handcrafted Frozen Chicken",
                            UpdatedAt = new DateTime(2022, 11, 4, 23, 50, 1, 85, DateTimeKind.Local).AddTicks(7353),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 11, 4, 20, 16, 965, DateTimeKind.Local).AddTicks(5285),
                            Description = "Repellat quod ipsam ",
                            Title = "Ergonomic Concrete Bike",
                            UpdatedAt = new DateTime(2022, 8, 21, 1, 32, 30, 168, DateTimeKind.Local).AddTicks(1833),
                            ownerId = 1
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Alfred51@yahoo.com",
                            Name = "Florence Crona",
                            Password = "mBFlK5WhSb"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Garnet3@yahoo.com",
                            Name = "Kieran Schowalter",
                            Password = "YbIYHeN6DD"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Crystal_Runte@gmail.com",
                            Name = "Alfred Grant",
                            Password = "6VNhGVBWB_"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Domenico34@yahoo.com",
                            Name = "Caroline Hoeger",
                            Password = "OLwykXljuE"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Matilde29@gmail.com",
                            Name = "Neoma Torphy",
                            Password = "HzhKEqL5bK"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("ownerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
