// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208214857_new4")]
    partial class new4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 16, 21, 17, 51, 40, DateTimeKind.Local).AddTicks(5886),
                            Description = "Sequi iusto omnis am",
                            ProjectRefId = 2,
                            Title = "Handmade Wooden Ball",
                            UpdatedAt = new DateTime(2022, 10, 6, 8, 7, 28, 411, DateTimeKind.Local).AddTicks(372)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 24, 23, 44, 17, 831, DateTimeKind.Local).AddTicks(4276),
                            Description = "Enim inventore reici",
                            ProjectRefId = 8,
                            Title = "Awesome Concrete Fish",
                            UpdatedAt = new DateTime(2022, 10, 10, 2, 27, 56, 89, DateTimeKind.Local).AddTicks(1490)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 27, 9, 33, 58, 358, DateTimeKind.Local).AddTicks(8997),
                            Description = "Est quia aut odit do",
                            ProjectRefId = 10,
                            Title = "Gorgeous Fresh Gloves",
                            UpdatedAt = new DateTime(2022, 10, 5, 10, 39, 11, 471, DateTimeKind.Local).AddTicks(4349)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 28, 17, 30, 24, 903, DateTimeKind.Local).AddTicks(5220),
                            Description = "Quo amet consequuntu",
                            ProjectRefId = 4,
                            Title = "Handmade Granite Shoes",
                            UpdatedAt = new DateTime(2022, 4, 22, 18, 11, 43, 373, DateTimeKind.Local).AddTicks(1170)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 3, 15, 3, 17, 47, 916, DateTimeKind.Local).AddTicks(6045),
                            Description = "Beatae commodi repel",
                            ProjectRefId = 4,
                            Title = "Rustic Granite Cheese",
                            UpdatedAt = new DateTime(2022, 9, 2, 21, 14, 46, 688, DateTimeKind.Local).AddTicks(5291)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 14, 1, 32, 20, 64, DateTimeKind.Local).AddTicks(9940),
                            Description = "Voluptatum asperiore",
                            ProjectRefId = 5,
                            Title = "Practical Fresh Bike",
                            UpdatedAt = new DateTime(2022, 11, 30, 18, 16, 48, 494, DateTimeKind.Local).AddTicks(592)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 5, 11, 5, 16, 35, 486, DateTimeKind.Local).AddTicks(2518),
                            Description = "Rerum aut natus quid",
                            ProjectRefId = 1,
                            Title = "Fantastic Cotton Hat",
                            UpdatedAt = new DateTime(2022, 9, 14, 5, 1, 38, 799, DateTimeKind.Local).AddTicks(3760)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 7, 15, 11, 2, 8, 43, DateTimeKind.Local).AddTicks(956),
                            Description = "Eligendi neque cumqu",
                            ProjectRefId = 3,
                            Title = "Awesome Rubber Towels",
                            UpdatedAt = new DateTime(2022, 8, 14, 18, 0, 26, 666, DateTimeKind.Local).AddTicks(5931)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 3, 12, 50, 53, 609, DateTimeKind.Local).AddTicks(2748),
                            Description = "Et tempore itaque cu",
                            ProjectRefId = 8,
                            Title = "Small Granite Shirt",
                            UpdatedAt = new DateTime(2023, 1, 20, 4, 52, 9, 697, DateTimeKind.Local).AddTicks(3697)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 2, 23, 17, 35, 12, 446, DateTimeKind.Local).AddTicks(108),
                            Description = "Qui amet sed vel por",
                            ProjectRefId = 3,
                            Title = "Refined Wooden Salad",
                            UpdatedAt = new DateTime(2023, 1, 8, 6, 5, 57, 855, DateTimeKind.Local).AddTicks(9702)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ownerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 8, 5, 50, 54, 432, DateTimeKind.Local).AddTicks(4155),
                            Description = "Explicabo est dolore",
                            Title = "Licensed Fresh Table",
                            UpdatedAt = new DateTime(2022, 8, 16, 23, 13, 46, 373, DateTimeKind.Local).AddTicks(2010),
                            ownerId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 11, 42, 33, 131, DateTimeKind.Local).AddTicks(2082),
                            Description = "Quas beatae veniam d",
                            Title = "Rustic Steel Tuna",
                            UpdatedAt = new DateTime(2022, 4, 20, 16, 34, 8, 384, DateTimeKind.Local).AddTicks(7997),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 2, 12, 3, 53, 53, 129, DateTimeKind.Local).AddTicks(1670),
                            Description = "Iusto voluptas simil",
                            Title = "Practical Cotton Shoes",
                            UpdatedAt = new DateTime(2023, 1, 25, 1, 26, 14, 778, DateTimeKind.Local).AddTicks(743),
                            ownerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 9, 10, 44, 59, 898, DateTimeKind.Local).AddTicks(9459),
                            Description = "At est a quam ut ips",
                            Title = "Gorgeous Frozen Car",
                            UpdatedAt = new DateTime(2022, 10, 29, 5, 36, 9, 394, DateTimeKind.Local).AddTicks(8190),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 22, 6, 26, 51, 18, DateTimeKind.Local).AddTicks(395),
                            Description = "Voluptas expedita mo",
                            Title = "Incredible Concrete Chips",
                            UpdatedAt = new DateTime(2022, 3, 12, 7, 59, 12, 497, DateTimeKind.Local).AddTicks(142),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 22, 19, 31, 45, 52, DateTimeKind.Local).AddTicks(883),
                            Description = "Et est harum beatae ",
                            Title = "Small Fresh Pants",
                            UpdatedAt = new DateTime(2022, 7, 30, 7, 38, 41, 374, DateTimeKind.Local).AddTicks(8042),
                            ownerId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 7, 29, 6, 36, 11, 655, DateTimeKind.Local).AddTicks(4502),
                            Description = "In et assumenda porr",
                            Title = "Handcrafted Wooden Ball",
                            UpdatedAt = new DateTime(2022, 12, 31, 15, 18, 54, 423, DateTimeKind.Local).AddTicks(5650),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 20, 18, 24, 4, 846, DateTimeKind.Local).AddTicks(4365),
                            Description = "Nulla vitae repudian",
                            Title = "Unbranded Soft Pizza",
                            UpdatedAt = new DateTime(2022, 5, 13, 4, 9, 28, 134, DateTimeKind.Local).AddTicks(2778),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 2, 12, 18, 46, 1, 638, DateTimeKind.Local).AddTicks(4538),
                            Description = "Aliquam blanditiis e",
                            Title = "Intelligent Fresh Soap",
                            UpdatedAt = new DateTime(2022, 12, 6, 8, 9, 41, 692, DateTimeKind.Local).AddTicks(5904),
                            ownerId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 2, 17, 21, 38, 52, 59, DateTimeKind.Local).AddTicks(6618),
                            Description = "Corporis doloremque ",
                            Title = "Incredible Fresh Shirt",
                            UpdatedAt = new DateTime(2022, 8, 2, 15, 45, 1, 846, DateTimeKind.Local).AddTicks(929),
                            ownerId = 5
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Shane2@yahoo.com",
                            Name = "Jaylan Tillman",
                            Password = "3SQqpEfUIT"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Vilma.Bartoletti@hotmail.com",
                            Name = "Jairo Shanahan",
                            Password = "qOgZjM9SwO"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Kevin88@yahoo.com",
                            Name = "Roma Ebert",
                            Password = "To_5gOLIN3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Gertrude.Jakubowski88@yahoo.com",
                            Name = "Adell Purdy",
                            Password = "hp5ntEDUgJ"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Lennie.Russel87@hotmail.com",
                            Name = "Anastasia Bosco",
                            Password = "icwMXXvAV9"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
