// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230212223657_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 25, 13, 5, 24, 201, DateTimeKind.Local).AddTicks(4805),
                            Description = "Corrupti nesciunt qu",
                            ProjectId = 6,
                            Title = "Licensed Fresh Towels",
                            UpdatedAt = new DateTime(2022, 9, 1, 22, 42, 18, 876, DateTimeKind.Local).AddTicks(2255)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 24, 19, 48, 23, 596, DateTimeKind.Local).AddTicks(740),
                            Description = "Nemo et nihil odio q",
                            ProjectId = 2,
                            Title = "Ergonomic Frozen Fish",
                            UpdatedAt = new DateTime(2022, 5, 9, 1, 44, 53, 590, DateTimeKind.Local).AddTicks(2829)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 23, 10, 53, 53, 102, DateTimeKind.Local).AddTicks(6710),
                            Description = "Ducimus quasi sit om",
                            ProjectId = 6,
                            Title = "Intelligent Metal Sausages",
                            UpdatedAt = new DateTime(2023, 1, 19, 20, 50, 34, 244, DateTimeKind.Local).AddTicks(7101)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 11, 3, 22, 26, 296, DateTimeKind.Local).AddTicks(1567),
                            Description = "Fuga illum necessita",
                            ProjectId = 8,
                            Title = "Sleek Wooden Cheese",
                            UpdatedAt = new DateTime(2022, 8, 31, 14, 10, 7, 418, DateTimeKind.Local).AddTicks(9423)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 8, 20, 12, 55, 27, 510, DateTimeKind.Local).AddTicks(8187),
                            Description = "Iure iusto rem tempo",
                            ProjectId = 5,
                            Title = "Generic Fresh Gloves",
                            UpdatedAt = new DateTime(2022, 9, 1, 13, 28, 3, 466, DateTimeKind.Local).AddTicks(602)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 11, 4, 9, 15, 25, 509, DateTimeKind.Local).AddTicks(4080),
                            Description = "Sequi sapiente aut o",
                            ProjectId = 9,
                            Title = "Handcrafted Soft Table",
                            UpdatedAt = new DateTime(2022, 8, 19, 23, 23, 42, 703, DateTimeKind.Local).AddTicks(6001)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 12, 30, 1, 22, 42, 363, DateTimeKind.Local).AddTicks(356),
                            Description = "Repellendus ut et qu",
                            ProjectId = 4,
                            Title = "Rustic Plastic Sausages",
                            UpdatedAt = new DateTime(2022, 3, 27, 3, 42, 0, 426, DateTimeKind.Local).AddTicks(9197)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 22, 21, 0, 19, 391, DateTimeKind.Local).AddTicks(4373),
                            Description = "Sit tempore incidunt",
                            ProjectId = 9,
                            Title = "Fantastic Granite Pants",
                            UpdatedAt = new DateTime(2022, 4, 17, 6, 22, 8, 393, DateTimeKind.Local).AddTicks(2607)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 2, 9, 19, 38, 28, 353, DateTimeKind.Local).AddTicks(701),
                            Description = "Et illum nemo laudan",
                            ProjectId = 1,
                            Title = "Practical Steel Tuna",
                            UpdatedAt = new DateTime(2022, 3, 13, 21, 47, 6, 585, DateTimeKind.Local).AddTicks(3112)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 8, 0, 51, 38, 108, DateTimeKind.Local).AddTicks(258),
                            Description = "Repudiandae quaerat ",
                            ProjectId = 7,
                            Title = "Tasty Cotton Tuna",
                            UpdatedAt = new DateTime(2022, 9, 4, 6, 28, 12, 944, DateTimeKind.Local).AddTicks(1944)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 27, 10, 53, 4, 698, DateTimeKind.Local).AddTicks(1940),
                            Description = "Quod consequatur rep",
                            OwnerId = 2,
                            Title = "Generic Wooden Mouse",
                            UpdatedAt = new DateTime(2022, 8, 16, 20, 12, 41, 928, DateTimeKind.Local).AddTicks(4860)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 11, 30, 18, 39, 49, 799, DateTimeKind.Local).AddTicks(4991),
                            Description = "Repudiandae dolorum ",
                            OwnerId = 2,
                            Title = "Handmade Frozen Mouse",
                            UpdatedAt = new DateTime(2022, 11, 10, 11, 51, 8, 830, DateTimeKind.Local).AddTicks(7439)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 19, 15, 9, 14, 895, DateTimeKind.Local).AddTicks(1211),
                            Description = "Nulla et rerum enim ",
                            OwnerId = 2,
                            Title = "Refined Cotton Shoes",
                            UpdatedAt = new DateTime(2022, 4, 29, 2, 16, 56, 883, DateTimeKind.Local).AddTicks(9536)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 11, 11, 17, 43, 44, 525, DateTimeKind.Local).AddTicks(7612),
                            Description = "Quo pariatur illo qu",
                            OwnerId = 1,
                            Title = "Generic Steel Table",
                            UpdatedAt = new DateTime(2023, 1, 16, 11, 20, 45, 101, DateTimeKind.Local).AddTicks(9491)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 2, 20, 1, 26, 33, 323, DateTimeKind.Local).AddTicks(5722),
                            Description = "Dolorem quisquam qua",
                            OwnerId = 2,
                            Title = "Awesome Metal Shoes",
                            UpdatedAt = new DateTime(2023, 1, 16, 23, 18, 33, 345, DateTimeKind.Local).AddTicks(2009)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 16, 2, 53, 32, 920, DateTimeKind.Local).AddTicks(4183),
                            Description = "Aliquam similique of",
                            OwnerId = 4,
                            Title = "Fantastic Wooden Cheese",
                            UpdatedAt = new DateTime(2022, 3, 25, 8, 59, 24, 276, DateTimeKind.Local).AddTicks(6162)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 12, 12, 11, 55, 9, 197, DateTimeKind.Local).AddTicks(9428),
                            Description = "Ullam maiores assume",
                            OwnerId = 5,
                            Title = "Handcrafted Plastic Shoes",
                            UpdatedAt = new DateTime(2022, 5, 23, 5, 12, 8, 887, DateTimeKind.Local).AddTicks(4847)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 2, 17, 8, 51, 15, 156, DateTimeKind.Local).AddTicks(2995),
                            Description = "Quo asperiores ullam",
                            OwnerId = 5,
                            Title = "Ergonomic Plastic Bike",
                            UpdatedAt = new DateTime(2022, 9, 24, 12, 55, 11, 649, DateTimeKind.Local).AddTicks(3162)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 20, 1, 53, 50, 573, DateTimeKind.Local).AddTicks(8230),
                            Description = "Vero saepe et. Quis ",
                            OwnerId = 3,
                            Title = "Unbranded Cotton Gloves",
                            UpdatedAt = new DateTime(2022, 4, 1, 2, 19, 13, 998, DateTimeKind.Local).AddTicks(780)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 12, 16, 22, 41, 42, 651, DateTimeKind.Local).AddTicks(9659),
                            Description = "Sapiente eos non qui",
                            OwnerId = 5,
                            Title = "Tasty Fresh Bike",
                            UpdatedAt = new DateTime(2022, 8, 16, 2, 32, 50, 732, DateTimeKind.Local).AddTicks(3799)
                        });
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Kenton_Hansen85@yahoo.com",
                            Name = "Eileen Streich",
                            Password = "W4h2EeVDro",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "Mattie65@yahoo.com",
                            Name = "Deja Ruecker",
                            Password = "6V6UMbK9kP",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "Nyah_Nolan@yahoo.com",
                            Name = "Unique Glover",
                            Password = "ZJhl3U9nxH",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "Providenci17@gmail.com",
                            Name = "Blair Romaguera",
                            Password = "dhDdWownGW",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "Stan_Jenkins71@yahoo.com",
                            Name = "Kali Lakin",
                            Password = "Z5uuJOTjcy",
                            RoleId = 0
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Participators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colab.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
