// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208201339_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 12, 10, 14, 0, 40, 498, DateTimeKind.Local).AddTicks(5276),
                            Description = "Repudiandae doloremq",
                            ProjectId = 3,
                            Title = "Handmade Fresh Shirt",
                            UpdatedAt = new DateTime(2022, 5, 10, 3, 56, 40, 792, DateTimeKind.Local).AddTicks(9603)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 8, 19, 4, 58, 873, DateTimeKind.Local).AddTicks(924),
                            Description = "Ratione officia dese",
                            ProjectId = 14,
                            Title = "Licensed Wooden Shirt",
                            UpdatedAt = new DateTime(2022, 2, 18, 12, 47, 20, 979, DateTimeKind.Local).AddTicks(6636)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 17, 11, 33, 49, 625, DateTimeKind.Local).AddTicks(6837),
                            Description = "Excepturi accusamus ",
                            ProjectId = 8,
                            Title = "Gorgeous Plastic Chicken",
                            UpdatedAt = new DateTime(2023, 1, 12, 7, 4, 33, 685, DateTimeKind.Local).AddTicks(8862)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 2, 25, 12, 13, 45, 470, DateTimeKind.Local).AddTicks(3122),
                            Description = "Corrupti ipsum ipsam",
                            ProjectId = 12,
                            Title = "Sleek Steel Keyboard",
                            UpdatedAt = new DateTime(2022, 10, 13, 7, 52, 1, 394, DateTimeKind.Local).AddTicks(6247)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 4, 17, 11, 50, 52, 93, DateTimeKind.Local).AddTicks(362),
                            Description = "Voluptates sequi per",
                            ProjectId = 20,
                            Title = "Ergonomic Granite Ball",
                            UpdatedAt = new DateTime(2022, 6, 5, 5, 16, 38, 34, DateTimeKind.Local).AddTicks(8182)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 5, 6, 22, 11, 6, 72, DateTimeKind.Local).AddTicks(436),
                            Description = "Voluptas totam praes",
                            ProjectId = 6,
                            Title = "Intelligent Metal Towels",
                            UpdatedAt = new DateTime(2022, 7, 27, 6, 24, 32, 38, DateTimeKind.Local).AddTicks(8642)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 5, 21, 16, 27, 29, 682, DateTimeKind.Local).AddTicks(5008),
                            Description = "Molestias quis quas ",
                            ProjectId = 4,
                            Title = "Intelligent Metal Table",
                            UpdatedAt = new DateTime(2023, 1, 11, 12, 59, 59, 676, DateTimeKind.Local).AddTicks(9439)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 3, 24, 3, 10, 19, 718, DateTimeKind.Local).AddTicks(9876),
                            Description = "Consequatur illo aut",
                            ProjectId = 18,
                            Title = "Awesome Steel Salad",
                            UpdatedAt = new DateTime(2022, 10, 20, 2, 23, 38, 165, DateTimeKind.Local).AddTicks(6987)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 2, 4, 10, 56, 33, 524, DateTimeKind.Local).AddTicks(3875),
                            Description = "Pariatur accusantium",
                            ProjectId = 17,
                            Title = "Small Steel Chips",
                            UpdatedAt = new DateTime(2022, 6, 29, 16, 28, 52, 354, DateTimeKind.Local).AddTicks(4801)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 9, 11, 16, 19, 38, 958, DateTimeKind.Local).AddTicks(119),
                            Description = "Cumque accusamus per",
                            ProjectId = 5,
                            Title = "Gorgeous Plastic Bacon",
                            UpdatedAt = new DateTime(2022, 11, 2, 5, 31, 54, 900, DateTimeKind.Local).AddTicks(9736)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 15, 6, 54, 53, 753, DateTimeKind.Local).AddTicks(3250),
                            Description = "Architecto impedit q",
                            ProjectId = 3,
                            Title = "Generic Concrete Fish",
                            UpdatedAt = new DateTime(2022, 12, 6, 23, 22, 23, 746, DateTimeKind.Local).AddTicks(776)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 6, 15, 14, 58, 54, 680, DateTimeKind.Local).AddTicks(7445),
                            Description = "Amet sed molestias a",
                            ProjectId = 14,
                            Title = "Handcrafted Cotton Car",
                            UpdatedAt = new DateTime(2022, 10, 27, 10, 6, 9, 704, DateTimeKind.Local).AddTicks(6368)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 11, 14, 26, 6, 725, DateTimeKind.Local).AddTicks(5702),
                            Description = "Aperiam sapiente ut ",
                            ProjectId = 20,
                            Title = "Tasty Wooden Gloves",
                            UpdatedAt = new DateTime(2022, 2, 21, 13, 46, 14, 960, DateTimeKind.Local).AddTicks(5331)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 11, 21, 5, 56, 6, 298, DateTimeKind.Local).AddTicks(5716),
                            Description = "Voluptate consequatu",
                            ProjectId = 2,
                            Title = "Practical Rubber Hat",
                            UpdatedAt = new DateTime(2022, 11, 26, 22, 2, 24, 738, DateTimeKind.Local).AddTicks(426)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 6, 8, 11, 38, 38, 939, DateTimeKind.Local).AddTicks(2053),
                            Description = "Quia voluptatem quod",
                            ProjectId = 14,
                            Title = "Handcrafted Fresh Sausages",
                            UpdatedAt = new DateTime(2022, 8, 9, 13, 14, 8, 993, DateTimeKind.Local).AddTicks(5423)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 9, 20, 16, 40, 49, 420, DateTimeKind.Local).AddTicks(1309),
                            Description = "Totam rerum voluptat",
                            ProjectId = 11,
                            Title = "Sleek Fresh Soap",
                            UpdatedAt = new DateTime(2022, 4, 14, 20, 5, 0, 179, DateTimeKind.Local).AddTicks(1113)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 11, 4, 13, 28, 51, 461, DateTimeKind.Local).AddTicks(5475),
                            Description = "Molestiae optio sapi",
                            ProjectId = 17,
                            Title = "Handcrafted Soft Pants",
                            UpdatedAt = new DateTime(2022, 10, 22, 18, 25, 35, 218, DateTimeKind.Local).AddTicks(5027)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 7, 28, 22, 38, 23, 869, DateTimeKind.Local).AddTicks(2619),
                            Description = "Eaque voluptatum ali",
                            ProjectId = 10,
                            Title = "Sleek Frozen Sausages",
                            UpdatedAt = new DateTime(2022, 11, 22, 21, 26, 48, 770, DateTimeKind.Local).AddTicks(7766)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 7, 9, 22, 41, 59, 353, DateTimeKind.Local).AddTicks(3135),
                            Description = "Libero voluptatem pe",
                            ProjectId = 10,
                            Title = "Ergonomic Frozen Chicken",
                            UpdatedAt = new DateTime(2022, 11, 12, 6, 45, 3, 777, DateTimeKind.Local).AddTicks(4013)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 10, 28, 3, 29, 45, 846, DateTimeKind.Local).AddTicks(599),
                            Description = "Consequatur vel dele",
                            ProjectId = 8,
                            Title = "Ergonomic Rubber Shoes",
                            UpdatedAt = new DateTime(2022, 11, 2, 5, 36, 29, 126, DateTimeKind.Local).AddTicks(8016)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 11, 15, 9, 2, 4, 506, DateTimeKind.Local).AddTicks(3313),
                            Description = "Aliquid voluptatem q",
                            OwnerId = 3,
                            Title = "Refined Concrete Bike",
                            UpdatedAt = new DateTime(2022, 3, 24, 13, 27, 37, 705, DateTimeKind.Local).AddTicks(7059)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 11, 18, 15, 9, 28, 422, DateTimeKind.Local).AddTicks(8728),
                            Description = "Nihil quibusdam et a",
                            OwnerId = 4,
                            Title = "Generic Metal Gloves",
                            UpdatedAt = new DateTime(2022, 7, 29, 5, 19, 52, 355, DateTimeKind.Local).AddTicks(8809)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 19, 3, 53, 227, DateTimeKind.Local).AddTicks(9567),
                            Description = "Et id explicabo inci",
                            OwnerId = 1,
                            Title = "Incredible Soft Hat",
                            UpdatedAt = new DateTime(2023, 1, 12, 18, 7, 11, 124, DateTimeKind.Local).AddTicks(4695)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 8, 9, 4, 54, 47, 338, DateTimeKind.Local).AddTicks(7457),
                            Description = "Nihil illo ad dolore",
                            OwnerId = 3,
                            Title = "Unbranded Rubber Shoes",
                            UpdatedAt = new DateTime(2022, 5, 31, 10, 38, 50, 88, DateTimeKind.Local).AddTicks(6478)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 16, 18, 50, 28, 784, DateTimeKind.Local).AddTicks(1748),
                            Description = "Hic voluptatem atque",
                            OwnerId = 4,
                            Title = "Ergonomic Granite Bike",
                            UpdatedAt = new DateTime(2022, 4, 27, 13, 3, 53, 490, DateTimeKind.Local).AddTicks(2909)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 20, 4, 1, 7, 725, DateTimeKind.Local).AddTicks(4208),
                            Description = "Iste natus explicabo",
                            OwnerId = 3,
                            Title = "Fantastic Cotton Pants",
                            UpdatedAt = new DateTime(2022, 8, 7, 9, 3, 47, 762, DateTimeKind.Local).AddTicks(1482)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 8, 3, 21, 46, 53, 128, DateTimeKind.Local).AddTicks(5195),
                            Description = "Qui sed sit ut reici",
                            OwnerId = 3,
                            Title = "Sleek Wooden Mouse",
                            UpdatedAt = new DateTime(2022, 3, 18, 4, 4, 26, 119, DateTimeKind.Local).AddTicks(6753)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 7, 12, 12, 36, 33, 514, DateTimeKind.Local).AddTicks(5402),
                            Description = "Et consequatur incid",
                            OwnerId = 3,
                            Title = "Refined Concrete Table",
                            UpdatedAt = new DateTime(2022, 5, 20, 19, 14, 59, 217, DateTimeKind.Local).AddTicks(801)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 11, 27, 16, 31, 24, 6, DateTimeKind.Local).AddTicks(1670),
                            Description = "Et rerum quos quibus",
                            OwnerId = 5,
                            Title = "Generic Cotton Salad",
                            UpdatedAt = new DateTime(2023, 1, 26, 2, 55, 36, 551, DateTimeKind.Local).AddTicks(7496)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 6, 8, 38, 54, 799, DateTimeKind.Local).AddTicks(2868),
                            Description = "Dolores maxime eaque",
                            OwnerId = 2,
                            Title = "Incredible Fresh Towels",
                            UpdatedAt = new DateTime(2022, 5, 22, 15, 38, 49, 749, DateTimeKind.Local).AddTicks(7682)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 6, 0, 44, 33, 963, DateTimeKind.Local).AddTicks(2757),
                            Description = "Sed quaerat quos ali",
                            OwnerId = 2,
                            Title = "Small Plastic Shirt",
                            UpdatedAt = new DateTime(2022, 5, 10, 9, 42, 0, 706, DateTimeKind.Local).AddTicks(7903)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 11, 5, 6, 59, 6, 188, DateTimeKind.Local).AddTicks(7464),
                            Description = "Repudiandae laborios",
                            OwnerId = 1,
                            Title = "Sleek Granite Car",
                            UpdatedAt = new DateTime(2022, 12, 27, 20, 20, 16, 64, DateTimeKind.Local).AddTicks(1422)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 3, 15, 3, 41, 54, 972, DateTimeKind.Local).AddTicks(2770),
                            Description = "Quia delectus sit cu",
                            OwnerId = 4,
                            Title = "Gorgeous Metal Fish",
                            UpdatedAt = new DateTime(2022, 2, 17, 15, 39, 23, 354, DateTimeKind.Local).AddTicks(268)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 11, 26, 23, 55, 13, 636, DateTimeKind.Local).AddTicks(5218),
                            Description = "Sunt ut enim vel dic",
                            OwnerId = 4,
                            Title = "Practical Wooden Keyboard",
                            UpdatedAt = new DateTime(2022, 12, 12, 1, 57, 45, 441, DateTimeKind.Local).AddTicks(9344)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 11, 14, 44, 18, 410, DateTimeKind.Local).AddTicks(9899),
                            Description = "Rem commodi rem. Dol",
                            OwnerId = 5,
                            Title = "Licensed Fresh Tuna",
                            UpdatedAt = new DateTime(2022, 11, 11, 4, 42, 55, 93, DateTimeKind.Local).AddTicks(767)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 4, 11, 10, 23, 14, 937, DateTimeKind.Local).AddTicks(8793),
                            Description = "Ad dolorem in. Eius ",
                            OwnerId = 4,
                            Title = "Small Fresh Computer",
                            UpdatedAt = new DateTime(2022, 10, 31, 4, 3, 50, 187, DateTimeKind.Local).AddTicks(2555)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 4, 19, 7, 56, 31, 22, DateTimeKind.Local).AddTicks(8969),
                            Description = "Praesentium fugit au",
                            OwnerId = 4,
                            Title = "Handmade Cotton Salad",
                            UpdatedAt = new DateTime(2022, 10, 14, 7, 12, 13, 110, DateTimeKind.Local).AddTicks(7858)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 8, 30, 13, 30, 28, 390, DateTimeKind.Local).AddTicks(2457),
                            Description = "Quis incidunt verita",
                            OwnerId = 3,
                            Title = "Generic Soft Salad",
                            UpdatedAt = new DateTime(2022, 4, 16, 15, 13, 7, 201, DateTimeKind.Local).AddTicks(4434)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 4, 30, 13, 8, 21, 596, DateTimeKind.Local).AddTicks(4823),
                            Description = "Ea vel libero vel. A",
                            OwnerId = 5,
                            Title = "Fantastic Plastic Chicken",
                            UpdatedAt = new DateTime(2022, 6, 3, 0, 6, 30, 42, DateTimeKind.Local).AddTicks(2985)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 7, 30, 1, 2, 3, 30, DateTimeKind.Local).AddTicks(2282),
                            Description = "Commodi quia cum. Mo",
                            OwnerId = 4,
                            Title = "Rustic Plastic Cheese",
                            UpdatedAt = new DateTime(2022, 12, 11, 14, 8, 2, 615, DateTimeKind.Local).AddTicks(3497)
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Janelle.Swift60@yahoo.com",
                            Name = "Madisyn Dickinson",
                            Password = "SCl9SMvi2c"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Stevie22@yahoo.com",
                            Name = "Emery Carter",
                            Password = "iw0u9aRjEI"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Rylee_Towne@gmail.com",
                            Name = "Ariel Jaskolski",
                            Password = "k6eTQL1KZe"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Adolf_Gusikowski@yahoo.com",
                            Name = "Noelia Parker",
                            Password = "vMeSvnQqcm"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Cicero.Huel13@hotmail.com",
                            Name = "Schuyler Windler",
                            Password = "bTBiBW3H9b"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
