// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208034434_haha")]
    partial class haha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 12, 6, 31, 42, 47, DateTimeKind.Local).AddTicks(9996),
                            Description = "Sed quasi corrupti l",
                            ProjectId = 1,
                            Title = "Awesome Soft Gloves",
                            UpdatedAt = new DateTime(2022, 6, 29, 17, 24, 44, 999, DateTimeKind.Local).AddTicks(9641)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 3, 11, 6, 5, 16, 664, DateTimeKind.Local).AddTicks(7997),
                            Description = "Placeat sequi est. F",
                            ProjectId = 7,
                            Title = "Small Plastic Computer",
                            UpdatedAt = new DateTime(2022, 10, 25, 0, 41, 23, 373, DateTimeKind.Local).AddTicks(1426)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 11, 17, 16, 43, 6, DateTimeKind.Local).AddTicks(5467),
                            Description = "Qui qui ad incidunt ",
                            ProjectId = 10,
                            Title = "Fantastic Soft Cheese",
                            UpdatedAt = new DateTime(2022, 12, 27, 11, 48, 59, 798, DateTimeKind.Local).AddTicks(7429)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 8, 29, 19, 3, 24, 425, DateTimeKind.Local).AddTicks(3637),
                            Description = "Dolores eaque quasi ",
                            ProjectId = 16,
                            Title = "Unbranded Plastic Cheese",
                            UpdatedAt = new DateTime(2022, 6, 20, 6, 21, 25, 125, DateTimeKind.Local).AddTicks(8584)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 3, 17, 39, 35, 749, DateTimeKind.Local).AddTicks(5689),
                            Description = "Illum omnis tempore ",
                            ProjectId = 15,
                            Title = "Refined Frozen Chair",
                            UpdatedAt = new DateTime(2022, 12, 28, 14, 28, 21, 388, DateTimeKind.Local).AddTicks(644)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 13, 22, 13, 24, 425, DateTimeKind.Local).AddTicks(2299),
                            Description = "Quasi voluptate quia",
                            ProjectId = 12,
                            Title = "Fantastic Cotton Shoes",
                            UpdatedAt = new DateTime(2023, 1, 7, 16, 57, 27, 961, DateTimeKind.Local).AddTicks(8249)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 8, 27, 6, 32, 2, 296, DateTimeKind.Local).AddTicks(5951),
                            Description = "Quo facilis maxime p",
                            ProjectId = 10,
                            Title = "Incredible Rubber Keyboard",
                            UpdatedAt = new DateTime(2022, 3, 20, 6, 2, 46, 806, DateTimeKind.Local).AddTicks(6494)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 2, 10, 37, 2, 867, DateTimeKind.Local).AddTicks(4773),
                            Description = "Nulla ut quia. Et su",
                            ProjectId = 5,
                            Title = "Unbranded Steel Hat",
                            UpdatedAt = new DateTime(2022, 7, 14, 10, 51, 57, 265, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 11, 27, 12, 52, 31, 81, DateTimeKind.Local).AddTicks(7363),
                            Description = "Aliquam est exceptur",
                            ProjectId = 10,
                            Title = "Small Cotton Shoes",
                            UpdatedAt = new DateTime(2022, 4, 27, 7, 34, 28, 250, DateTimeKind.Local).AddTicks(745)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 31, 21, 54, 54, 339, DateTimeKind.Local).AddTicks(994),
                            Description = "Dolores officiis pro",
                            ProjectId = 15,
                            Title = "Handmade Soft Salad",
                            UpdatedAt = new DateTime(2022, 2, 21, 10, 4, 4, 960, DateTimeKind.Local).AddTicks(5451)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 7, 19, 21, 13, 45, 904, DateTimeKind.Local).AddTicks(2734),
                            Description = "Eligendi aliquam exc",
                            ProjectId = 20,
                            Title = "Ergonomic Steel Gloves",
                            UpdatedAt = new DateTime(2022, 3, 27, 9, 7, 2, 197, DateTimeKind.Local).AddTicks(2506)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 9, 12, 23, 25, 42, 758, DateTimeKind.Local).AddTicks(7761),
                            Description = "Ut voluptates distin",
                            ProjectId = 16,
                            Title = "Sleek Metal Mouse",
                            UpdatedAt = new DateTime(2023, 1, 25, 6, 53, 14, 421, DateTimeKind.Local).AddTicks(550)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 5, 8, 0, 51, 39, 634, DateTimeKind.Local).AddTicks(1467),
                            Description = "Numquam pariatur eaq",
                            ProjectId = 11,
                            Title = "Ergonomic Concrete Chair",
                            UpdatedAt = new DateTime(2022, 12, 8, 19, 20, 22, 346, DateTimeKind.Local).AddTicks(9203)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 3, 25, 23, 34, 23, 238, DateTimeKind.Local).AddTicks(899),
                            Description = "Dolore nam eligendi ",
                            ProjectId = 5,
                            Title = "Fantastic Plastic Hat",
                            UpdatedAt = new DateTime(2022, 3, 5, 21, 26, 19, 733, DateTimeKind.Local).AddTicks(9501)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 11, 2, 8, 43, 4, 237, DateTimeKind.Local).AddTicks(7392),
                            Description = "Unde non ut voluptat",
                            ProjectId = 14,
                            Title = "Fantastic Cotton Towels",
                            UpdatedAt = new DateTime(2022, 7, 30, 23, 38, 3, 373, DateTimeKind.Local).AddTicks(6188)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 11, 14, 9, 41, 41, 714, DateTimeKind.Local).AddTicks(8732),
                            Description = "Inventore quibusdam ",
                            ProjectId = 12,
                            Title = "Awesome Fresh Ball",
                            UpdatedAt = new DateTime(2022, 7, 6, 21, 41, 34, 799, DateTimeKind.Local).AddTicks(8542)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 10, 21, 22, 49, 18, 745, DateTimeKind.Local).AddTicks(3024),
                            Description = "Occaecati voluptatib",
                            ProjectId = 3,
                            Title = "Tasty Wooden Soap",
                            UpdatedAt = new DateTime(2022, 6, 12, 16, 35, 18, 507, DateTimeKind.Local).AddTicks(8655)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 9, 6, 1, 6, 11, 139, DateTimeKind.Local).AddTicks(8264),
                            Description = "Vel cupiditate exped",
                            ProjectId = 9,
                            Title = "Rustic Fresh Car",
                            UpdatedAt = new DateTime(2022, 3, 13, 6, 26, 0, 195, DateTimeKind.Local).AddTicks(758)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 5, 22, 23, 8, 23, 895, DateTimeKind.Local).AddTicks(6964),
                            Description = "Recusandae quos impe",
                            ProjectId = 3,
                            Title = "Handcrafted Soft Computer",
                            UpdatedAt = new DateTime(2023, 2, 4, 6, 16, 16, 427, DateTimeKind.Local).AddTicks(5806)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 3, 7, 19, 0, 17, 514, DateTimeKind.Local).AddTicks(7539),
                            Description = "Aut aut voluptatem r",
                            ProjectId = 10,
                            Title = "Tasty Concrete Pizza",
                            UpdatedAt = new DateTime(2022, 11, 23, 16, 37, 27, 221, DateTimeKind.Local).AddTicks(538)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 23, 21, 3, 18, 923, DateTimeKind.Local).AddTicks(5276),
                            Description = "Aliquid suscipit qui",
                            OwnerId = 5,
                            Title = "Generic Cotton Chair",
                            UpdatedAt = new DateTime(2022, 8, 21, 12, 57, 16, 921, DateTimeKind.Local).AddTicks(6419)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 8, 26, 7, 24, 26, 825, DateTimeKind.Local).AddTicks(6747),
                            Description = "Rem numquam sed dist",
                            OwnerId = 5,
                            Title = "Fantastic Fresh Ball",
                            UpdatedAt = new DateTime(2022, 4, 4, 1, 4, 44, 964, DateTimeKind.Local).AddTicks(3253)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 13, 10, 34, 13, 769, DateTimeKind.Local).AddTicks(9674),
                            Description = "Quidem in in ea a of",
                            OwnerId = 1,
                            Title = "Sleek Fresh Fish",
                            UpdatedAt = new DateTime(2022, 6, 11, 20, 3, 48, 207, DateTimeKind.Local).AddTicks(7405)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 4, 25, 20, 10, 19, 7, DateTimeKind.Local).AddTicks(4290),
                            Description = "Ut laborum dolorum p",
                            OwnerId = 3,
                            Title = "Refined Frozen Cheese",
                            UpdatedAt = new DateTime(2023, 1, 27, 20, 7, 37, 547, DateTimeKind.Local).AddTicks(7464)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 4, 6, 2, 43, 1, 379, DateTimeKind.Local).AddTicks(9554),
                            Description = "Sit et vero. Dicta l",
                            OwnerId = 1,
                            Title = "Ergonomic Concrete Sausages",
                            UpdatedAt = new DateTime(2022, 4, 23, 16, 58, 3, 917, DateTimeKind.Local).AddTicks(6585)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 8, 22, 36, 27, 553, DateTimeKind.Local).AddTicks(3186),
                            Description = "Commodi pariatur rem",
                            OwnerId = 2,
                            Title = "Gorgeous Steel Shoes",
                            UpdatedAt = new DateTime(2022, 3, 16, 19, 49, 30, 807, DateTimeKind.Local).AddTicks(8439)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 2, 19, 9, 59, 49, 305, DateTimeKind.Local).AddTicks(9862),
                            Description = "Necessitatibus qui l",
                            OwnerId = 5,
                            Title = "Fantastic Rubber Bike",
                            UpdatedAt = new DateTime(2023, 1, 29, 22, 53, 8, 129, DateTimeKind.Local).AddTicks(2916)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 6, 0, 32, 32, 860, DateTimeKind.Local).AddTicks(4923),
                            Description = "Blanditiis fuga et a",
                            OwnerId = 2,
                            Title = "Generic Granite Mouse",
                            UpdatedAt = new DateTime(2022, 4, 9, 18, 3, 48, 510, DateTimeKind.Local).AddTicks(6923)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 11, 26, 11, 11, 15, 579, DateTimeKind.Local).AddTicks(1292),
                            Description = "Corporis in neque ex",
                            OwnerId = 4,
                            Title = "Intelligent Granite Salad",
                            UpdatedAt = new DateTime(2022, 6, 30, 20, 28, 28, 427, DateTimeKind.Local).AddTicks(5528)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 22, 0, 7, 26, 988, DateTimeKind.Local).AddTicks(6786),
                            Description = "Eveniet doloremque r",
                            OwnerId = 4,
                            Title = "Incredible Cotton Computer",
                            UpdatedAt = new DateTime(2022, 4, 12, 11, 9, 11, 392, DateTimeKind.Local).AddTicks(6302)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 12, 11, 18, 27, 29, 607, DateTimeKind.Local).AddTicks(6106),
                            Description = "Dolorem perferendis ",
                            OwnerId = 4,
                            Title = "Unbranded Cotton Car",
                            UpdatedAt = new DateTime(2022, 10, 9, 16, 38, 15, 761, DateTimeKind.Local).AddTicks(9670)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 2, 23, 3, 4, 58, 747, DateTimeKind.Local).AddTicks(6650),
                            Description = "Corrupti ratione dic",
                            OwnerId = 4,
                            Title = "Unbranded Fresh Shirt",
                            UpdatedAt = new DateTime(2022, 12, 11, 0, 16, 38, 311, DateTimeKind.Local).AddTicks(219)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 9, 12, 16, 48, 43, 715, DateTimeKind.Local).AddTicks(9596),
                            Description = "Eum officiis est in ",
                            OwnerId = 5,
                            Title = "Incredible Soft Keyboard",
                            UpdatedAt = new DateTime(2022, 7, 22, 22, 4, 59, 635, DateTimeKind.Local).AddTicks(7596)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 4, 0, 46, 52, 315, DateTimeKind.Local).AddTicks(4887),
                            Description = "Voluptate reiciendis",
                            OwnerId = 4,
                            Title = "Awesome Concrete Sausages",
                            UpdatedAt = new DateTime(2022, 2, 21, 12, 9, 16, 615, DateTimeKind.Local).AddTicks(1350)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 12, 19, 51, 49, 513, DateTimeKind.Local).AddTicks(7110),
                            Description = "Eaque ipsam non inci",
                            OwnerId = 3,
                            Title = "Licensed Concrete Tuna",
                            UpdatedAt = new DateTime(2022, 5, 31, 0, 15, 21, 902, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 3, 17, 11, 3, 35, 24, DateTimeKind.Local).AddTicks(856),
                            Description = "Adipisci quos autem ",
                            OwnerId = 3,
                            Title = "Gorgeous Rubber Shoes",
                            UpdatedAt = new DateTime(2022, 5, 1, 20, 48, 6, 159, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 6, 11, 15, 24, 14, 656, DateTimeKind.Local).AddTicks(588),
                            Description = "Illum ea accusamus. ",
                            OwnerId = 1,
                            Title = "Incredible Wooden Keyboard",
                            UpdatedAt = new DateTime(2023, 1, 23, 1, 41, 30, 510, DateTimeKind.Local).AddTicks(7336)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 3, 29, 7, 26, 5, 498, DateTimeKind.Local).AddTicks(2714),
                            Description = "Dignissimos necessit",
                            OwnerId = 2,
                            Title = "Fantastic Fresh Gloves",
                            UpdatedAt = new DateTime(2022, 2, 14, 21, 38, 23, 704, DateTimeKind.Local).AddTicks(5292)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 11, 7, 9, 59, 40, 364, DateTimeKind.Local).AddTicks(5627),
                            Description = "Dolor et dolorem et ",
                            OwnerId = 5,
                            Title = "Ergonomic Wooden Pants",
                            UpdatedAt = new DateTime(2022, 6, 12, 2, 10, 48, 667, DateTimeKind.Local).AddTicks(4980)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 3, 19, 2, 33, 48, 913, DateTimeKind.Local).AddTicks(6584),
                            Description = "Beatae corrupti aut ",
                            OwnerId = 3,
                            Title = "Incredible Soft Cheese",
                            UpdatedAt = new DateTime(2023, 1, 14, 15, 40, 43, 782, DateTimeKind.Local).AddTicks(1451)
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Rosemary_Hickle5@yahoo.com",
                            Name = "Vena Walsh",
                            Password = "_vXg4k2x71"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Hubert42@gmail.com",
                            Name = "Helene Torp",
                            Password = "0b5YYSq6G9"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Brooks46@yahoo.com",
                            Name = "Constance Mueller",
                            Password = "sjIzImTl2c"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Eldon.Murray@gmail.com",
                            Name = "Shanon Auer",
                            Password = "N0xdxHFpL5"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Katlynn.Considine@gmail.com",
                            Name = "Ima Braun",
                            Password = "VDozahKnYq"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
