// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230403032733_thismysql")]
    partial class thismysql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 24, 12, 0, 10, 847, DateTimeKind.Local).AddTicks(3247),
                            Description = "Eos quod et dolores ",
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Small Frozen Pants",
                            UpdatedAt = new DateTime(2022, 5, 20, 21, 59, 42, 706, DateTimeKind.Local).AddTicks(7279)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 16, 14, 24, 14, 382, DateTimeKind.Local).AddTicks(7778),
                            Description = "A error autem vel do",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Small Concrete Fish",
                            UpdatedAt = new DateTime(2023, 2, 8, 10, 40, 20, 44, DateTimeKind.Local).AddTicks(4031)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 16, 41, 12, 73, DateTimeKind.Local).AddTicks(734),
                            Description = "Commodi est aperiam ",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Incredible Soft Car",
                            UpdatedAt = new DateTime(2022, 11, 1, 8, 46, 16, 174, DateTimeKind.Local).AddTicks(3489)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 28, 13, 55, 52, 771, DateTimeKind.Local).AddTicks(7339),
                            Description = "Ut voluptate qui cup",
                            IsCompleted = true,
                            ProjectId = 1,
                            Title = "Rustic Metal Cheese",
                            UpdatedAt = new DateTime(2022, 7, 17, 22, 17, 23, 639, DateTimeKind.Local).AddTicks(6881)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 6, 4, 2, 14, 56, 944, DateTimeKind.Local).AddTicks(4289),
                            Description = "Delectus voluptatum ",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Generic Concrete Salad",
                            UpdatedAt = new DateTime(2022, 7, 31, 18, 57, 10, 845, DateTimeKind.Local).AddTicks(7501)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 18, 23, 49, 54, 778, DateTimeKind.Local).AddTicks(1090),
                            Description = "Numquam non vitae ve",
                            IsCompleted = true,
                            ProjectId = 10,
                            Title = "Sleek Plastic Chicken",
                            UpdatedAt = new DateTime(2022, 12, 1, 3, 46, 16, 226, DateTimeKind.Local).AddTicks(4175)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 23, 21, 42, 44, 789, DateTimeKind.Local).AddTicks(8429),
                            Description = "Consequatur quibusda",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Gorgeous Steel Chicken",
                            UpdatedAt = new DateTime(2023, 1, 9, 10, 33, 25, 395, DateTimeKind.Local).AddTicks(915)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 15, 6, 5, 54, 555, DateTimeKind.Local).AddTicks(5254),
                            Description = "Et facere aut nesciu",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Tasty Fresh Mouse",
                            UpdatedAt = new DateTime(2022, 10, 1, 5, 6, 8, 747, DateTimeKind.Local).AddTicks(8236)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 2, 17, 1, 48, 25, 895, DateTimeKind.Local).AddTicks(4737),
                            Description = "Corrupti saepe tenet",
                            IsCompleted = true,
                            ProjectId = 3,
                            Title = "Tasty Cotton Chicken",
                            UpdatedAt = new DateTime(2022, 7, 9, 18, 15, 37, 116, DateTimeKind.Local).AddTicks(6995)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 23, 5, 36, 24, 243, DateTimeKind.Local).AddTicks(284),
                            Description = "Dolorem illo officia",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Generic Granite Chicken",
                            UpdatedAt = new DateTime(2023, 3, 1, 7, 0, 44, 49, DateTimeKind.Local).AddTicks(5593)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 3, 31, 16, 31, 42, 166, DateTimeKind.Local).AddTicks(8658),
                            Description = "Sint iste repellendu",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Handmade Soft Tuna",
                            UpdatedAt = new DateTime(2022, 8, 27, 5, 43, 33, 545, DateTimeKind.Local).AddTicks(6507)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 6, 19, 9, 52, 34, 741, DateTimeKind.Local).AddTicks(1557),
                            Description = "Quia asperiores volu",
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Small Plastic Hat",
                            UpdatedAt = new DateTime(2022, 10, 18, 16, 13, 14, 466, DateTimeKind.Local).AddTicks(3101)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 9, 13, 5, 38, 19, 641, DateTimeKind.Local).AddTicks(2807),
                            Description = "Quas ipsum iure dolo",
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Rustic Plastic Soap",
                            UpdatedAt = new DateTime(2022, 5, 6, 15, 3, 31, 309, DateTimeKind.Local).AddTicks(7957)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 7, 3, 18, 42, 20, 739, DateTimeKind.Local).AddTicks(4853),
                            Description = "Consequatur quasi id",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Incredible Soft Bacon",
                            UpdatedAt = new DateTime(2023, 2, 1, 22, 50, 55, 551, DateTimeKind.Local).AddTicks(4133)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 16, 21, 58, 29, 499, DateTimeKind.Local).AddTicks(4709),
                            Description = "Velit excepturi reru",
                            IsCompleted = false,
                            ProjectId = 8,
                            Title = "Small Concrete Pants",
                            UpdatedAt = new DateTime(2023, 3, 30, 3, 16, 6, 355, DateTimeKind.Local).AddTicks(7477)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 12, 10, 0, 11, 34, 662, DateTimeKind.Local).AddTicks(9044),
                            Description = "Nesciunt consequatur",
                            IsCompleted = true,
                            ProjectId = 8,
                            Title = "Licensed Steel Keyboard",
                            UpdatedAt = new DateTime(2022, 10, 9, 19, 14, 1, 514, DateTimeKind.Local).AddTicks(7354)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 11, 2, 7, 52, 47, 357, DateTimeKind.Local).AddTicks(3522),
                            Description = "Voluptate saepe corr",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Handcrafted Fresh Sausages",
                            UpdatedAt = new DateTime(2023, 2, 22, 3, 28, 29, 778, DateTimeKind.Local).AddTicks(8475)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 10, 6, 8, 58, 56, 466, DateTimeKind.Local).AddTicks(892),
                            Description = "Cupiditate at nobis ",
                            IsCompleted = true,
                            ProjectId = 3,
                            Title = "Intelligent Soft Soap",
                            UpdatedAt = new DateTime(2022, 10, 13, 16, 59, 19, 427, DateTimeKind.Local).AddTicks(3426)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 10, 25, 12, 53, 16, 359, DateTimeKind.Local).AddTicks(6027),
                            Description = "Eius et placeat accu",
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Awesome Concrete Gloves",
                            UpdatedAt = new DateTime(2022, 5, 1, 4, 29, 21, 904, DateTimeKind.Local).AddTicks(7371)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 6, 27, 23, 5, 49, 154, DateTimeKind.Local).AddTicks(9369),
                            Description = "Ad recusandae iure s",
                            IsCompleted = false,
                            ProjectId = 8,
                            Title = "Generic Frozen Fish",
                            UpdatedAt = new DateTime(2022, 8, 25, 6, 51, 57, 44, DateTimeKind.Local).AddTicks(1782)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 8, 11, 22, 1, 4, DateTimeKind.Local).AddTicks(8979),
                            Description = "Alias saepe corporis",
                            Title = "Refined Frozen Table",
                            UpdatedAt = new DateTime(2022, 5, 24, 13, 18, 52, 264, DateTimeKind.Local).AddTicks(3679)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 21, 5, 49, 24, 806, DateTimeKind.Local).AddTicks(7642),
                            Description = "Laudantium quia plac",
                            Title = "Intelligent Concrete Computer",
                            UpdatedAt = new DateTime(2022, 7, 27, 12, 30, 9, 28, DateTimeKind.Local).AddTicks(875)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 30, 19, 12, 7, 581, DateTimeKind.Local).AddTicks(2126),
                            Description = "Maiores repudiandae ",
                            Title = "Practical Cotton Towels",
                            UpdatedAt = new DateTime(2022, 4, 4, 15, 45, 36, 13, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 11, 5, 19, 25, 29, 986, DateTimeKind.Local).AddTicks(115),
                            Description = "Officia eius cum hic",
                            Title = "Ergonomic Steel Car",
                            UpdatedAt = new DateTime(2022, 5, 22, 13, 35, 15, 312, DateTimeKind.Local).AddTicks(3449)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 8, 19, 20, 19, 52, 944, DateTimeKind.Local).AddTicks(6809),
                            Description = "Accusantium iusto ve",
                            Title = "Unbranded Plastic Chips",
                            UpdatedAt = new DateTime(2022, 12, 19, 21, 20, 46, 360, DateTimeKind.Local).AddTicks(4752)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 22, 18, 57, 31, 589, DateTimeKind.Local).AddTicks(5498),
                            Description = "Placeat adipisci ear",
                            Title = "Fantastic Frozen Salad",
                            UpdatedAt = new DateTime(2022, 11, 20, 2, 32, 16, 131, DateTimeKind.Local).AddTicks(9004)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 6, 23, 16, 54, 29, 396, DateTimeKind.Local).AddTicks(8883),
                            Description = "Et quia odit autem e",
                            Title = "Fantastic Metal Computer",
                            UpdatedAt = new DateTime(2022, 10, 19, 22, 48, 19, 481, DateTimeKind.Local).AddTicks(6089)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 12, 2, 10, 28, 31, 532, DateTimeKind.Local).AddTicks(3789),
                            Description = "Magnam reiciendis et",
                            Title = "Rustic Steel Keyboard",
                            UpdatedAt = new DateTime(2023, 2, 23, 17, 25, 7, 727, DateTimeKind.Local).AddTicks(3465)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 4, 4, 6, 1, 53, 451, DateTimeKind.Local).AddTicks(2049),
                            Description = "Ullam culpa voluptat",
                            Title = "Licensed Cotton Computer",
                            UpdatedAt = new DateTime(2023, 3, 13, 2, 52, 10, 507, DateTimeKind.Local).AddTicks(2081)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 11, 8, 17, 32, 14, 162, DateTimeKind.Local).AddTicks(3555),
                            Description = "Nesciunt consequatur",
                            Title = "Practical Concrete Chair",
                            UpdatedAt = new DateTime(2022, 11, 22, 1, 9, 14, 211, DateTimeKind.Local).AddTicks(1009)
                        });
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Dameon.Crona@gmail.com",
                            IsAdmin = false,
                            Name = "Alvis Mayert",
                            Password = "rh57Up58LO"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Juliet.Treutel@hotmail.com",
                            IsAdmin = false,
                            Name = "Karine Brakus",
                            Password = "X8VDFlVAQ1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Jed_Gottlieb59@hotmail.com",
                            IsAdmin = false,
                            Name = "Shyann Nitzsche",
                            Password = "V5Y6FN4BfK"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Archibald30@hotmail.com",
                            IsAdmin = false,
                            Name = "Benny Krajcik",
                            Password = "qmSPLufyWY"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Cassandre_OReilly@hotmail.com",
                            IsAdmin = false,
                            Name = "Jalen Renner",
                            Password = "uBsLFvj7vM"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Participators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colab.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
