// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208225153_new5")]
    partial class new5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 15, 10, 53, 27, 834, DateTimeKind.Local).AddTicks(8215),
                            Description = "Ut est nulla. Nulla ",
                            ProjectId = 10,
                            Title = "Gorgeous Soft Computer",
                            UpdatedAt = new DateTime(2022, 11, 14, 15, 0, 6, 44, DateTimeKind.Local).AddTicks(608)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 24, 14, 43, 47, 42, DateTimeKind.Local).AddTicks(9665),
                            Description = "Est ipsa beatae cupi",
                            ProjectId = 7,
                            Title = "Ergonomic Cotton Ball",
                            UpdatedAt = new DateTime(2022, 10, 30, 23, 14, 42, 783, DateTimeKind.Local).AddTicks(4808)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 4, 18, 2, 41, 16, 97, DateTimeKind.Local).AddTicks(2525),
                            Description = "Laudantium dolores e",
                            ProjectId = 5,
                            Title = "Generic Soft Tuna",
                            UpdatedAt = new DateTime(2022, 2, 13, 14, 13, 20, 85, DateTimeKind.Local).AddTicks(3759)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 20, 12, 34, 19, 897, DateTimeKind.Local).AddTicks(409),
                            Description = "Voluptatibus qui vol",
                            ProjectId = 2,
                            Title = "Practical Steel Chair",
                            UpdatedAt = new DateTime(2022, 8, 8, 12, 7, 33, 248, DateTimeKind.Local).AddTicks(9059)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 2, 28, 12, 5, 54, 5, DateTimeKind.Local).AddTicks(4005),
                            Description = "Minima perferendis s",
                            ProjectId = 6,
                            Title = "Intelligent Soft Shoes",
                            UpdatedAt = new DateTime(2022, 10, 27, 13, 0, 18, 601, DateTimeKind.Local).AddTicks(364)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 3, 18, 3, 39, 47, 978, DateTimeKind.Local).AddTicks(3344),
                            Description = "Sit explicabo blandi",
                            ProjectId = 9,
                            Title = "Unbranded Steel Shoes",
                            UpdatedAt = new DateTime(2022, 11, 14, 1, 35, 0, 547, DateTimeKind.Local).AddTicks(2712)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 2, 20, 6, 46, 43, 329, DateTimeKind.Local).AddTicks(7359),
                            Description = "Fugiat quis consequa",
                            ProjectId = 1,
                            Title = "Handcrafted Plastic Ball",
                            UpdatedAt = new DateTime(2022, 3, 14, 8, 46, 5, 69, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 8, 24, 20, 26, 44, 4, DateTimeKind.Local).AddTicks(3934),
                            Description = "Officia fugit quia d",
                            ProjectId = 2,
                            Title = "Fantastic Granite Salad",
                            UpdatedAt = new DateTime(2022, 8, 30, 0, 52, 57, 557, DateTimeKind.Local).AddTicks(429)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 13, 23, 11, 37, 945, DateTimeKind.Local).AddTicks(1293),
                            Description = "Accusamus eaque culp",
                            ProjectId = 3,
                            Title = "Gorgeous Steel Pizza",
                            UpdatedAt = new DateTime(2022, 12, 1, 4, 3, 30, 492, DateTimeKind.Local).AddTicks(321)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 8, 23, 17, 59, 12, 287, DateTimeKind.Local).AddTicks(2694),
                            Description = "Cumque est et impedi",
                            ProjectId = 8,
                            Title = "Fantastic Rubber Cheese",
                            UpdatedAt = new DateTime(2022, 9, 1, 12, 52, 16, 304, DateTimeKind.Local).AddTicks(9374)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 7, 23, 14, 31, 45, 395, DateTimeKind.Local).AddTicks(3),
                            Description = "Omnis dolor recusand",
                            OwnerId = 3,
                            Title = "Practical Concrete Shoes",
                            UpdatedAt = new DateTime(2022, 11, 15, 21, 54, 33, 533, DateTimeKind.Local).AddTicks(6470)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 12, 20, 12, 45, 49, 648, DateTimeKind.Local).AddTicks(7102),
                            Description = "Dolorem est unde sap",
                            OwnerId = 1,
                            Title = "Awesome Plastic Mouse",
                            UpdatedAt = new DateTime(2022, 10, 16, 6, 54, 45, 411, DateTimeKind.Local).AddTicks(6689)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 3, 6, 2, 24, 20, 879, DateTimeKind.Local).AddTicks(6905),
                            Description = "Hic rerum nam molest",
                            OwnerId = 4,
                            Title = "Ergonomic Steel Shirt",
                            UpdatedAt = new DateTime(2022, 10, 26, 11, 18, 3, 606, DateTimeKind.Local).AddTicks(5939)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 5, 18, 19, 58, 8, 454, DateTimeKind.Local).AddTicks(70),
                            Description = "Illum cum sed volupt",
                            OwnerId = 3,
                            Title = "Practical Soft Keyboard",
                            UpdatedAt = new DateTime(2023, 1, 7, 13, 34, 25, 17, DateTimeKind.Local).AddTicks(1951)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 21, 15, 48, 45, 564, DateTimeKind.Local).AddTicks(5152),
                            Description = "Doloribus commodi vo",
                            OwnerId = 2,
                            Title = "Gorgeous Cotton Pants",
                            UpdatedAt = new DateTime(2022, 9, 13, 3, 27, 35, 786, DateTimeKind.Local).AddTicks(3260)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 6, 14, 47, 48, 16, DateTimeKind.Local).AddTicks(2700),
                            Description = "Quia atque error rer",
                            OwnerId = 4,
                            Title = "Intelligent Frozen Chicken",
                            UpdatedAt = new DateTime(2022, 10, 23, 23, 5, 58, 162, DateTimeKind.Local).AddTicks(5033)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 12, 22, 30, 0, 716, DateTimeKind.Local).AddTicks(5479),
                            Description = "Repudiandae itaque h",
                            OwnerId = 1,
                            Title = "Incredible Fresh Pizza",
                            UpdatedAt = new DateTime(2022, 6, 30, 13, 25, 51, 903, DateTimeKind.Local).AddTicks(6826)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 8, 12, 27, 52, 126, DateTimeKind.Local).AddTicks(8887),
                            Description = "Ipsa praesentium rep",
                            OwnerId = 1,
                            Title = "Ergonomic Soft Keyboard",
                            UpdatedAt = new DateTime(2022, 7, 11, 17, 31, 54, 478, DateTimeKind.Local).AddTicks(7688)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 9, 11, 3, 18, 2, 437, DateTimeKind.Local).AddTicks(6499),
                            Description = "Aut necessitatibus q",
                            OwnerId = 5,
                            Title = "Small Metal Shirt",
                            UpdatedAt = new DateTime(2022, 11, 1, 15, 45, 3, 775, DateTimeKind.Local).AddTicks(793)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 8, 10, 9, 48, 51, 789, DateTimeKind.Local).AddTicks(8718),
                            Description = "Quae reiciendis magn",
                            OwnerId = 5,
                            Title = "Refined Soft Sausages",
                            UpdatedAt = new DateTime(2022, 6, 2, 0, 50, 12, 588, DateTimeKind.Local).AddTicks(7442)
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Michelle_Glover@yahoo.com",
                            Name = "Rowena Harris",
                            Password = "l1i4EtSxcu"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Camille55@hotmail.com",
                            Name = "Kelli Smith",
                            Password = "7hI2SVsGwy"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Lauren.Jerde@gmail.com",
                            Name = "Hassie Cormier",
                            Password = "nSK0jQLdTv"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Evalyn_Jenkins@yahoo.com",
                            Name = "Audra Breitenberg",
                            Password = "hD4cksfwl9"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Rocky.Collins@yahoo.com",
                            Name = "Jaylan Cummerata",
                            Password = "6pY6u3m2V3"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", "owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
