// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230208201928_new2")]
    partial class new2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 15, 1, 32, 7, 451, DateTimeKind.Local).AddTicks(9713),
                            Description = "Quia quia reiciendis",
                            ProjectId = 10,
                            Title = "Ergonomic Granite Computer",
                            UpdatedAt = new DateTime(2022, 10, 30, 9, 35, 22, 96, DateTimeKind.Local).AddTicks(6475)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 2, 9, 46, 24, 325, DateTimeKind.Local).AddTicks(3690),
                            Description = "Quia neque officiis ",
                            ProjectId = 7,
                            Title = "Generic Soft Soap",
                            UpdatedAt = new DateTime(2022, 8, 26, 8, 51, 35, 400, DateTimeKind.Local).AddTicks(2862)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 2, 28, 2, 25, 5, 577, DateTimeKind.Local).AddTicks(1377),
                            Description = "Voluptas earum nostr",
                            ProjectId = 7,
                            Title = "Handcrafted Plastic Ball",
                            UpdatedAt = new DateTime(2022, 2, 21, 0, 2, 29, 120, DateTimeKind.Local).AddTicks(3473)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 5, 18, 51, 57, 972, DateTimeKind.Local).AddTicks(3001),
                            Description = "Harum totam sint et ",
                            ProjectId = 10,
                            Title = "Generic Cotton Towels",
                            UpdatedAt = new DateTime(2022, 5, 10, 15, 21, 29, 795, DateTimeKind.Local).AddTicks(4570)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 8, 9, 16, 13, 900, DateTimeKind.Local).AddTicks(5420),
                            Description = "Earum voluptates nih",
                            ProjectId = 4,
                            Title = "Sleek Concrete Keyboard",
                            UpdatedAt = new DateTime(2022, 5, 11, 3, 20, 43, 921, DateTimeKind.Local).AddTicks(9428)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 12, 19, 4, 11, 17, 198, DateTimeKind.Local).AddTicks(5763),
                            Description = "Sint dolorum rerum d",
                            ProjectId = 7,
                            Title = "Fantastic Granite Hat",
                            UpdatedAt = new DateTime(2022, 9, 11, 5, 0, 2, 961, DateTimeKind.Local).AddTicks(8507)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 11, 17, 38, 41, 464, DateTimeKind.Local).AddTicks(119),
                            Description = "Sit amet vitae qui s",
                            ProjectId = 8,
                            Title = "Licensed Cotton Keyboard",
                            UpdatedAt = new DateTime(2022, 4, 21, 12, 48, 43, 740, DateTimeKind.Local).AddTicks(3929)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 17, 5, 17, 47, 231, DateTimeKind.Local).AddTicks(6557),
                            Description = "Excepturi qui volupt",
                            ProjectId = 5,
                            Title = "Refined Soft Towels",
                            UpdatedAt = new DateTime(2022, 10, 16, 16, 35, 29, 385, DateTimeKind.Local).AddTicks(7707)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 7, 21, 1, 51, 25, 414, DateTimeKind.Local).AddTicks(6637),
                            Description = "Ea eligendi vitae po",
                            ProjectId = 10,
                            Title = "Practical Concrete Towels",
                            UpdatedAt = new DateTime(2022, 9, 20, 2, 24, 3, 99, DateTimeKind.Local).AddTicks(19)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 11, 22, 49, 20, 891, DateTimeKind.Local).AddTicks(9436),
                            Description = "Ipsum porro rem nemo",
                            ProjectId = 9,
                            Title = "Small Metal Sausages",
                            UpdatedAt = new DateTime(2023, 2, 5, 21, 49, 28, 395, DateTimeKind.Local).AddTicks(7583)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 3, 17, 7, 26, 4, 71, DateTimeKind.Local).AddTicks(5693),
                            Description = "Rerum aut numquam au",
                            Title = "Tasty Steel Ball",
                            UpdatedAt = new DateTime(2022, 4, 18, 6, 1, 46, 230, DateTimeKind.Local).AddTicks(204),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 12, 17, 2, 1, 156, DateTimeKind.Local).AddTicks(6236),
                            Description = "Ullam numquam eos al",
                            Title = "Practical Plastic Computer",
                            UpdatedAt = new DateTime(2023, 1, 13, 7, 7, 23, 82, DateTimeKind.Local).AddTicks(2059),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 11, 26, 3, 41, 14, 669, DateTimeKind.Local).AddTicks(9908),
                            Description = "Neque quisquam aperi",
                            Title = "Generic Rubber Car",
                            UpdatedAt = new DateTime(2022, 2, 13, 19, 48, 36, 169, DateTimeKind.Local).AddTicks(2440),
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 3, 15, 13, 29, 19, 341, DateTimeKind.Local).AddTicks(976),
                            Description = "Vel est rerum volupt",
                            Title = "Handmade Wooden Bike",
                            UpdatedAt = new DateTime(2022, 2, 9, 3, 25, 34, 268, DateTimeKind.Local).AddTicks(4262),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 11, 18, 14, 12, 5, 132, DateTimeKind.Local).AddTicks(9030),
                            Description = "Doloribus cupiditate",
                            Title = "Practical Concrete Chicken",
                            UpdatedAt = new DateTime(2022, 8, 1, 19, 13, 7, 764, DateTimeKind.Local).AddTicks(8805),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 19, 12, 47, 23, 744, DateTimeKind.Local).AddTicks(1761),
                            Description = "Corporis consequatur",
                            Title = "Ergonomic Cotton Gloves",
                            UpdatedAt = new DateTime(2022, 7, 9, 7, 54, 30, 500, DateTimeKind.Local).AddTicks(9044),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 12, 14, 11, 49, 32, 263, DateTimeKind.Local).AddTicks(7806),
                            Description = "Officiis qui expedit",
                            Title = "Small Soft Pants",
                            UpdatedAt = new DateTime(2022, 6, 7, 23, 19, 20, 582, DateTimeKind.Local).AddTicks(9029),
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 2, 22, 57, 18, 379, DateTimeKind.Local).AddTicks(4088),
                            Description = "Sit est vel omnis vo",
                            Title = "Licensed Concrete Ball",
                            UpdatedAt = new DateTime(2022, 5, 17, 21, 14, 53, 973, DateTimeKind.Local).AddTicks(1001),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 4, 26, 13, 30, 32, 701, DateTimeKind.Local).AddTicks(114),
                            Description = "Culpa ipsam itaque h",
                            Title = "Awesome Concrete Chips",
                            UpdatedAt = new DateTime(2022, 12, 21, 23, 3, 38, 55, DateTimeKind.Local).AddTicks(2041),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 7, 29, 4, 14, 15, 461, DateTimeKind.Local).AddTicks(7205),
                            Description = "Illum itaque dicta e",
                            Title = "Intelligent Fresh Gloves",
                            UpdatedAt = new DateTime(2022, 10, 31, 16, 21, 16, 306, DateTimeKind.Local).AddTicks(9811),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Mireya27@gmail.com",
                            Name = "Karlie McCullough",
                            Password = "lZB6oTopUG"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Vallie_Schmeler@yahoo.com",
                            Name = "Allene Yost",
                            Password = "8kLpXdsBDi"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Loma_Schaden@yahoo.com",
                            Name = "Dariana Casper",
                            Password = "Yh1OYoWmxA"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Nathen45@gmail.com",
                            Name = "Kelton Tromp",
                            Password = "sbASngRG6b"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Darwin.Von33@gmail.com",
                            Name = "Jada Dietrich",
                            Password = "4Cx1VsE9gh"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.HasOne("Colab.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
