// <auto-generated />
using System;
using Colab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 7, 31, 41, 179, DateTimeKind.Local).AddTicks(541),
                            Description = "Reiciendis praesenti",
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Rustic Rubber Gloves",
                            UpdatedAt = new DateTime(2023, 2, 2, 11, 11, 44, 682, DateTimeKind.Local).AddTicks(9013)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 4, 40, 47, 81, DateTimeKind.Local).AddTicks(3529),
                            Description = "Veniam animi ipsa et",
                            IsCompleted = true,
                            ProjectId = 8,
                            Title = "Generic Granite Hat",
                            UpdatedAt = new DateTime(2023, 1, 11, 7, 35, 0, 163, DateTimeKind.Local).AddTicks(5045)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 8, 24, 5, 52, 12, 376, DateTimeKind.Local).AddTicks(8740),
                            Description = "Odit vel recusandae ",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Rustic Soft Pizza",
                            UpdatedAt = new DateTime(2022, 7, 15, 12, 37, 52, 42, DateTimeKind.Local).AddTicks(5326)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 11, 13, 15, 27, 24, 887, DateTimeKind.Local).AddTicks(3185),
                            Description = "Tempora et soluta no",
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Small Fresh Ball",
                            UpdatedAt = new DateTime(2022, 7, 16, 20, 6, 2, 295, DateTimeKind.Local).AddTicks(3726)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 18, 16, 18, 41, 703, DateTimeKind.Local).AddTicks(9437),
                            Description = "Hic consequatur dict",
                            IsCompleted = true,
                            ProjectId = 4,
                            Title = "Incredible Steel Chips",
                            UpdatedAt = new DateTime(2022, 3, 8, 9, 20, 23, 967, DateTimeKind.Local).AddTicks(4890)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 6, 14, 19, 42, 31, 788, DateTimeKind.Local).AddTicks(2044),
                            Description = "Quam soluta at volup",
                            IsCompleted = true,
                            ProjectId = 9,
                            Title = "Fantastic Fresh Table",
                            UpdatedAt = new DateTime(2022, 10, 11, 20, 18, 32, 702, DateTimeKind.Local).AddTicks(4396)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 8, 15, 5, 50, 44, 703, DateTimeKind.Local).AddTicks(523),
                            Description = "Dolor perspiciatis o",
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Small Cotton Pizza",
                            UpdatedAt = new DateTime(2022, 6, 24, 4, 39, 43, 358, DateTimeKind.Local).AddTicks(4272)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 30, 14, 44, 33, 402, DateTimeKind.Local).AddTicks(1939),
                            Description = "Ut et rerum dolores ",
                            IsCompleted = false,
                            ProjectId = 7,
                            Title = "Rustic Frozen Bacon",
                            UpdatedAt = new DateTime(2022, 8, 2, 20, 16, 35, 384, DateTimeKind.Local).AddTicks(9261)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 3, 2, 18, 12, 34, 817, DateTimeKind.Local).AddTicks(6046),
                            Description = "Quo odit incidunt er",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Handcrafted Wooden Keyboard",
                            UpdatedAt = new DateTime(2022, 11, 23, 4, 13, 44, 565, DateTimeKind.Local).AddTicks(6291)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 11, 17, 22, 44, 22, 765, DateTimeKind.Local).AddTicks(9824),
                            Description = "Atque rem iure numqu",
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Intelligent Soft Salad",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 52, 13, 405, DateTimeKind.Local).AddTicks(8637)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 6, 23, 19, 56, 14, 868, DateTimeKind.Local).AddTicks(1320),
                            Description = "Soluta atque atque l",
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "Licensed Wooden Salad",
                            UpdatedAt = new DateTime(2022, 8, 23, 0, 45, 17, 351, DateTimeKind.Local).AddTicks(6740)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 12, 3, 0, 44, 19, 604, DateTimeKind.Local).AddTicks(918),
                            Description = "Ex eos porro recusan",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Fantastic Plastic Tuna",
                            UpdatedAt = new DateTime(2022, 2, 13, 18, 30, 45, 692, DateTimeKind.Local).AddTicks(4903)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 3, 19, 18, 23, 27, 211, DateTimeKind.Local).AddTicks(7408),
                            Description = "Necessitatibus delen",
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "Refined Metal Chips",
                            UpdatedAt = new DateTime(2022, 2, 25, 21, 12, 15, 302, DateTimeKind.Local).AddTicks(857)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 3, 30, 17, 5, 25, 459, DateTimeKind.Local).AddTicks(153),
                            Description = "Perferendis velit en",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Handcrafted Concrete Mouse",
                            UpdatedAt = new DateTime(2022, 12, 21, 19, 18, 52, 186, DateTimeKind.Local).AddTicks(7130)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 4, 21, 22, 11, 48, 706, DateTimeKind.Local).AddTicks(9190),
                            Description = "Laboriosam optio aut",
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Intelligent Soft Computer",
                            UpdatedAt = new DateTime(2023, 2, 10, 16, 26, 46, 770, DateTimeKind.Local).AddTicks(8561)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 2, 9, 23, 36, 42, 818, DateTimeKind.Local).AddTicks(3391),
                            Description = "Nisi exercitationem ",
                            IsCompleted = true,
                            ProjectId = 1,
                            Title = "Ergonomic Cotton Hat",
                            UpdatedAt = new DateTime(2022, 12, 23, 9, 32, 53, 26, DateTimeKind.Local).AddTicks(2361)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 2, 8, 19, 55, 11, 985, DateTimeKind.Local).AddTicks(373),
                            Description = "Laudantium iure pari",
                            IsCompleted = true,
                            ProjectId = 6,
                            Title = "Generic Soft Chicken",
                            UpdatedAt = new DateTime(2022, 5, 20, 19, 55, 6, 991, DateTimeKind.Local).AddTicks(6930)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 8, 6, 10, 22, 12, 739, DateTimeKind.Local).AddTicks(8050),
                            Description = "Mollitia rem ducimus",
                            IsCompleted = true,
                            ProjectId = 8,
                            Title = "Rustic Concrete Mouse",
                            UpdatedAt = new DateTime(2022, 8, 7, 19, 13, 27, 571, DateTimeKind.Local).AddTicks(6930)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 8, 15, 16, 26, 12, 539, DateTimeKind.Local).AddTicks(7700),
                            Description = "Rem est libero labor",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Unbranded Metal Gloves",
                            UpdatedAt = new DateTime(2022, 2, 18, 8, 12, 52, 101, DateTimeKind.Local).AddTicks(9125)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 12, 16, 4, 19, 52, 870, DateTimeKind.Local).AddTicks(5243),
                            Description = "Sapiente quo numquam",
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Licensed Granite Tuna",
                            UpdatedAt = new DateTime(2022, 3, 16, 9, 12, 42, 511, DateTimeKind.Local).AddTicks(7383)
                        });
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 8, 31, 1, 26, 52, 570, DateTimeKind.Local).AddTicks(927),
                            Description = "Iste similique quas ",
                            Title = "Unbranded Wooden Salad",
                            UpdatedAt = new DateTime(2022, 10, 2, 9, 11, 5, 489, DateTimeKind.Local).AddTicks(57)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 24, 14, 10, 33, 137, DateTimeKind.Local).AddTicks(1585),
                            Description = "Blanditiis quia aut.",
                            Title = "Handcrafted Granite Fish",
                            UpdatedAt = new DateTime(2022, 3, 24, 3, 12, 27, 383, DateTimeKind.Local).AddTicks(972)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 8, 16, 27, 22, 721, DateTimeKind.Local).AddTicks(8863),
                            Description = "Sed aut culpa vel ex",
                            Title = "Refined Granite Chips",
                            UpdatedAt = new DateTime(2022, 7, 16, 23, 4, 31, 516, DateTimeKind.Local).AddTicks(3906)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 7, 30, 4, 30, 39, 643, DateTimeKind.Local).AddTicks(4294),
                            Description = "Voluptas iusto expli",
                            Title = "Ergonomic Plastic Soap",
                            UpdatedAt = new DateTime(2022, 11, 26, 14, 32, 42, 663, DateTimeKind.Local).AddTicks(7201)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 12, 10, 12, 51, 964, DateTimeKind.Local).AddTicks(6521),
                            Description = "Officiis exercitatio",
                            Title = "Small Cotton Chips",
                            UpdatedAt = new DateTime(2022, 9, 15, 22, 16, 9, 454, DateTimeKind.Local).AddTicks(5194)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 7, 10, 21, 40, 813, DateTimeKind.Local).AddTicks(6767),
                            Description = "Voluptas quasi hic n",
                            Title = "Gorgeous Frozen Shirt",
                            UpdatedAt = new DateTime(2022, 3, 5, 8, 11, 45, 667, DateTimeKind.Local).AddTicks(2517)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 11, 18, 22, 45, 29, 935, DateTimeKind.Local).AddTicks(8127),
                            Description = "Rem ea fugit. Accusa",
                            Title = "Fantastic Fresh Table",
                            UpdatedAt = new DateTime(2022, 3, 1, 18, 13, 17, 745, DateTimeKind.Local).AddTicks(464)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 24, 14, 28, 50, 693, DateTimeKind.Local).AddTicks(2027),
                            Description = "In eveniet facilis a",
                            Title = "Handmade Soft Soap",
                            UpdatedAt = new DateTime(2022, 3, 22, 12, 53, 3, 596, DateTimeKind.Local).AddTicks(6928)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 4, 19, 19, 34, 22, 521, DateTimeKind.Local).AddTicks(9008),
                            Description = "Ut est iusto est ali",
                            Title = "Generic Rubber Salad",
                            UpdatedAt = new DateTime(2022, 6, 23, 21, 26, 48, 797, DateTimeKind.Local).AddTicks(4798)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 1, 4, 23, 17, 360, DateTimeKind.Local).AddTicks(9417),
                            Description = "Eum vero reiciendis ",
                            Title = "Handcrafted Cotton Tuna",
                            UpdatedAt = new DateTime(2022, 6, 23, 13, 46, 29, 752, DateTimeKind.Local).AddTicks(1342)
                        });
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Isaias.Bednar95@gmail.com",
                            IsAdmin = false,
                            Name = "Turner Hansen",
                            Password = "c3DdkMNGO8"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Osborne.Pagac70@gmail.com",
                            IsAdmin = false,
                            Name = "Katelyn Gerhold",
                            Password = "OcV4c5V1dM"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Shanna_Luettgen@yahoo.com",
                            IsAdmin = false,
                            Name = "Urban Nienow",
                            Password = "AIs9F2DIvf"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Guiseppe_Vandervort65@yahoo.com",
                            IsAdmin = false,
                            Name = "Prince Hyatt",
                            Password = "iDDoMcGeS7"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Collin23@yahoo.com",
                            IsAdmin = false,
                            Name = "Alycia Anderson",
                            Password = "Jkd4ddtBhS"
                        });
                });

            modelBuilder.Entity("Colab.Models.Assignment", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Colab.Models.ProjectUser", b =>
                {
                    b.HasOne("Colab.Models.Project", "Project")
                        .WithMany("Participators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colab.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Colab.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Colab.Models.User", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
